import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { cancelReminderNotification, scheduleReminderNotification } from '../../../lib/notifications';
import { supabase } from '../../../lib/supabase';

type Horse = { id:string; name:string };
type Competition = { id:string; name:string; venue:string|null; class_name:string|null; discipline:string|null; competition_date:string; notes:string|null; status:'planned'|'completed'|'cancelled'; horse_id:string|null; result_rank:number|null; score:number|null; faults:number|null; result_notes:string|null };
const PREP=[{days:7,label:'Competition preparation — 7 days before'},{days:2,label:'Final preparation — 2 days before'},{days:0,label:'Competition day — check equipment & documents'}];

export default function CompetitionDetailScreen(){
 const { id } = useLocalSearchParams<{id:string}>();
 const [item,setItem]=useState<Competition|null>(null); const [horses,setHorses]=useState<Horse[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
 const [name,setName]=useState(''); const [venue,setVenue]=useState(''); const [className,setClassName]=useState(''); const [discipline,setDiscipline]=useState(''); const [date,setDate]=useState(''); const [time,setTime]=useState('09:00'); const [horseId,setHorseId]=useState(''); const [notes,setNotes]=useState('');
 const [rank,setRank]=useState(''); const [score,setScore]=useState(''); const [faults,setFaults]=useState(''); const [resultNotes,setResultNotes]=useState('');
 const load=useCallback(async()=>{ if(!id){setError('Competition not found.');setLoading(false);return} setLoading(true); const {data:{user}}=await supabase.auth.getUser(); if(!user){setError('Please sign in first.');setLoading(false);return} const [{data:c,error:e},{data:h}]=await Promise.all([supabase.from('competitions').select('id,name,venue,class_name,discipline,competition_date,notes,status,horse_id,result_rank,score,faults,result_notes').eq('id',id).eq('user_id',user.id).single(),supabase.from('horse_listings').select('id,name').eq('user_id',user.id).order('name')]); if(e){setError(e.message);setLoading(false);return} const x=c as Competition; setItem(x); setHorses((h??[]) as Horse[]); setName(x.name);setVenue(x.venue??'');setClassName(x.class_name??'');setDiscipline(x.discipline??''); const d=new Date(x.competition_date); setDate(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`);setTime(`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`);setHorseId(x.horse_id??'');setNotes(x.notes??'');setRank(x.result_rank==null?'':String(x.result_rank));setScore(x.score==null?'':String(x.score));setFaults(x.faults==null?'':String(x.faults));setResultNotes(x.result_notes??'');setLoading(false)},[id]);
 useEffect(()=>{void load()},[load]);
 async function syncPreparationReminders(competition:Competition){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:old}=await supabase.from('reminders').select('id').eq('competition_id',competition.id).eq('user_id',user.id);await Promise.all((old??[]).map(r=>cancelReminderNotification(r.id)));await supabase.from('reminders').delete().eq('competition_id',competition.id).eq('user_id',user.id);if(competition.status!=='planned')return;const d=new Date(competition.competition_date);const reminders=PREP.map(step=>({user_id:user.id,competition_id:competition.id,horse_id:competition.horse_id,title:`${step.label}: ${competition.name}`,description:[competition.venue,competition.class_name,competition.discipline].filter(Boolean).join(' • ')||null,reminder_type:'competition',due_at:new Date(d.getTime()-step.days*86400000).toISOString(),remind_before_minutes:0,status:'pending',enabled:true})).filter(r=>new Date(r.due_at).getTime()>Date.now());if(!reminders.length)return;const{data:created}=await supabase.from('reminders').insert(reminders).select('id,title,description,reminder_type,due_at,remind_before_minutes');if(created)await Promise.all(created.map(r=>scheduleReminderNotification(r)))}
 async function save(){setError(null);if(!item||!name.trim()||!date){setError('Competition name and date are required.');return}const d=new Date(`${date}T${time||'09:00'}:00`);if(Number.isNaN(d.getTime())){setError('Please use YYYY-MM-DD and HH:MM.');return}setSaving(true);const{data:{user}}=await supabase.auth.getUser();const{data:updated,error:e}=await supabase.from('competitions').update({name:name.trim(),venue:venue.trim()||null,class_name:className.trim()||null,discipline:discipline.trim()||null,competition_date:d.toISOString(),horse_id:horseId||null,notes:notes.trim()||null}).eq('id',item.id).eq('user_id',user?.id??'').select('id,name,venue,class_name,discipline,competition_date,notes,status,horse_id,result_rank,score,faults,result_notes').single();if(!e&&updated)await syncPreparationReminders(updated as Competition);setSaving(false);if(e)setError(e.message);else await load()}
 async function saveResult(){setError(null);if(!item)return;const r=rank.trim()?Number(rank):null,s=score.trim()?Number(score):null,f=faults.trim()?Number(faults):null;if(r!==null&&(!Number.isInteger(r)||r<1)){setError('Rank must be a whole number of 1 or higher.');return}if(s!==null&&(!Number.isFinite(s)||s<0)){setError('Score must be a valid non-negative number.');return}if(f!==null&&(!Number.isFinite(f)||f<0)){setError('Faults must be a valid non-negative number.');return}setSaving(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setError('Please sign in first.');setSaving(false);return}const{error:e}=await supabase.from('competitions').update({result_rank:r,score:s,faults:f,result_notes:resultNotes.trim()||null,status:'completed'}).eq('id',item.id).eq('user_id',user.id);if(!e){const{data:linked}=await supabase.from('reminders').select('id').eq('competition_id',item.id).eq('user_id',user.id);await Promise.all((linked??[]).map(x=>cancelReminderNotification(x.id)));await supabase.from('reminders').update({status:'completed',enabled:false}).eq('competition_id',item.id).eq('user_id',user.id)}setSaving(false);if(e)setError(e.message);else {await load();if(item.horse_id)router.push(`/(tabs)/horse/performance/${item.horse_id}`)}}
 async function setStatus(status:'cancelled'|'planned'){if(!item)return;setSaving(true);const{data:{user}}=await supabase.auth.getUser();const{error:e}=await supabase.from('competitions').update({status}).eq('id',item.id).eq('user_id',user?.id??'');if(!e&&status==='cancelled'){const{data:linked}=await supabase.from('reminders').select('id').eq('competition_id',item.id).eq('user_id',user?.id??'');await Promise.all((linked??[]).map(x=>cancelReminderNotification(x.id)));await supabase.from('reminders').update({status:'cancelled',enabled:false}).eq('competition_id',item.id).eq('user_id',user?.id??'')}if(!e&&status==='planned')await syncPreparationReminders({...item,status});setSaving(false);if(e)setError(e.message);else await load()}
 if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Loading competition…</Text></View>;
 if(!item)return <SafeAreaView style={styles.safe}><View style={styles.content}><Text style={styles.error}>{error??'Competition not found.'}</Text><Pressable onPress={()=>router.back()} style={styles.primary}><Text style={styles.primaryText}>Back</Text></Pressable></View></SafeAreaView>;
 const completed=item.status==='completed',cancelled=item.status==='cancelled',hasHorse=Boolean(item.horse_id),horseName=horses.find(h=>h.id===item.horse_id)?.name;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.brand}>SHABDIZ</Text><Text style={styles.title}>{item.name}</Text><View style={[styles.status,{backgroundColor:completed?'#E9F3EE':cancelled?'#F6E8E5':'#F1EFE9'}]}><Text style={styles.statusText}>{item.status}</Text></View>
 {hasHorse&&<View style={styles.readinessCard}><View style={styles.readinessCopy}><Text style={styles.readinessTitle}>🏆 Competition Readiness</Text><Text style={styles.readinessText}>{horseName?`${horseName} · training snapshot before the show`:'Review the training snapshot before the show.'}</Text></View><Pressable onPress={()=>router.push(`/(tabs)/competition/readiness/${item.id}`)} style={styles.readinessButton}><Text style={styles.readinessButtonText}>Open ›</Text></Pressable></View>}
 <View style={styles.card}><Text style={styles.section}>Competition details</Text><TextInput value={name} onChangeText={setName} placeholder="Competition name" style={styles.input}/><TextInput value={venue} onChangeText={setVenue} placeholder="Venue / location" style={styles.input}/><TextInput value={className} onChangeText={setClassName} placeholder="Class" style={styles.input}/><TextInput value={discipline} onChangeText={setDiscipline} placeholder="Discipline" style={styles.input}/><View style={styles.row}><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={[styles.input,styles.half]}/><TextInput value={time} onChangeText={setTime} placeholder="HH:MM" style={[styles.input,styles.half]}/></View><Text style={styles.label}>Horse</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><Pressable onPress={()=>setHorseId('')} style={[styles.chip,!horseId&&styles.active]}><Text style={[styles.chipText,!horseId&&styles.activeText]}>No horse</Text></Pressable>{horses.map(h=><Pressable key={h.id} onPress={()=>setHorseId(h.id)} style={[styles.chip,horseId===h.id&&styles.active]}><Text style={[styles.chipText,horseId===h.id&&styles.activeText]}>{h.name}</Text></Pressable>)}</ScrollView><TextInput value={notes} onChangeText={setNotes} placeholder="Competition notes" style={[styles.input,styles.notes]} multiline/><Pressable disabled={saving||cancelled} onPress={()=>void save()} style={[styles.primary,cancelled&&styles.disabled]}><Text style={styles.primaryText}>{saving?'Saving…':'Save competition'}</Text></Pressable></View>
 <View style={styles.card}><Text style={styles.section}>Result</Text><Text style={styles.hint}>After the show, record the result and performance.</Text><View style={styles.row}><TextInput value={rank} onChangeText={setRank} keyboardType="number-pad" placeholder="Rank" style={[styles.input,styles.third]}/><TextInput value={score} onChangeText={setScore} keyboardType="decimal-pad" placeholder="Score" style={[styles.input,styles.third]}/><TextInput value={faults} onChangeText={setFaults} keyboardType="decimal-pad" placeholder="Faults" style={[styles.input,styles.third]}/></View><TextInput value={resultNotes} onChangeText={setResultNotes} placeholder="Performance notes" style={[styles.input,styles.notes]} multiline/><Pressable disabled={saving||cancelled} onPress={()=>void saveResult()} style={[styles.primary,cancelled&&styles.disabled]}><Text style={styles.primaryText}>{completed?'Update result & view performance':'Save result & view performance'}</Text></Pressable>{completed&&<View style={styles.resultBox}><Text style={styles.resultTitle}>🏆 Recorded result</Text><Text style={styles.resultText}>{rank?`Rank ${rank}`:'Rank —'}  ·  {score?`Score ${score}`:'Score —'}  ·  {faults?`${faults} faults`:'Faults —'}</Text></View>}{completed&&hasHorse?<Pressable onPress={()=>router.push(`/(tabs)/horse/performance/${item.horse_id}`)} style={styles.performanceButton}><Text style={styles.performanceButtonText}>📈 View horse performance ›</Text></Pressable>:null}</View>
 <View style={styles.actions}>{item.status==='planned'&&<Pressable disabled={saving} onPress={()=>Alert.alert('Cancel competition?','This will mark the competition as cancelled and stop its preparation reminders.',[{text:'Keep',style:'cancel'},{text:'Cancel',style:'destructive',onPress:()=>void setStatus('cancelled')}])} style={styles.secondary}><Text style={styles.secondaryText}>Cancel competition</Text></Pressable>}{cancelled&&<Pressable disabled={saving} onPress={()=>void setStatus('planned')} style={styles.secondary}><Text style={styles.secondaryText}>Restore as planned</Text></Pressable>}</View>{error?<Text style={styles.error}>{error}</Text>:null}</ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F5F0'},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F5F0'},back:{color:'#0E5A45',fontWeight:'800',marginBottom:14},brand:{fontSize:30,fontWeight:'900',letterSpacing:2.5,color:'#0E5A45'},title:{marginTop:14,fontSize:30,fontWeight:'900'},status:{alignSelf:'flex-start',paddingHorizontal:12,paddingVertical:7,borderRadius:14,marginTop:10},statusText:{fontSize:12,fontWeight:'900',textTransform:'capitalize',color:'#0E5A45'},readinessCard:{marginTop:16,padding:16,borderRadius:19,backgroundColor:'#123F31',flexDirection:'row',alignItems:'center'},readinessCopy:{flex:1,paddingRight:10},readinessTitle:{fontSize:16,fontWeight:'900',color:'#FFF'},readinessText:{marginTop:5,fontSize:12,lineHeight:17,color:'#DCEBE5'},readinessButton:{paddingHorizontal:14,paddingVertical:10,borderRadius:13,backgroundColor:'#FFF'},readinessButtonText:{fontWeight:'900',color:'#123F31'},card:{marginTop:18,padding:18,borderRadius:22,backgroundColor:'#FFF'},section:{fontSize:20,fontWeight:'900',marginBottom:12},input:{minHeight:46,borderWidth:1,borderColor:'#DCD9D1',borderRadius:13,paddingHorizontal:12,backgroundColor:'#FAFAF8',fontSize:15,marginBottom:10},row:{flexDirection:'row',gap:8},half:{flex:1},third:{flex:1,minWidth:0},label:{fontSize:12,fontWeight:'800',color:'#777D79',marginBottom:7},chips:{gap:8,paddingBottom:5},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:16,backgroundColor:'#F1EFE9'},active:{backgroundColor:'#0E5A45'},chipText:{fontWeight:'800',color:'#555C58'},activeText:{color:'#FFF'},notes:{minHeight:80,paddingTop:12,textAlignVertical:'top'},primary:{marginTop:4,minHeight:50,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#0E5A45'},primaryText:{color:'#FFF',fontWeight:'900'},disabled:{opacity:.45},secondary:{minHeight:48,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF0EE',borderWidth:1,borderColor:'#E6C8C3'},secondaryText:{color:'#A33A2B',fontWeight:'900'},actions:{marginTop:16},resultBox:{marginTop:12,padding:14,borderRadius:15,backgroundColor:'#E9F3EE'},resultTitle:{fontWeight:'900',color:'#0E5A45'},resultText:{marginTop:5,fontWeight:'800',color:'#254E40'},performanceButton:{marginTop:12,minHeight:46,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#F1EFE9'},performanceButtonText:{fontWeight:'900',color:'#0E5A45'},hint:{fontSize:13,opacity:.6,marginBottom:12},muted:{marginTop:6,opacity:.55},error:{marginTop:12,color:'#A33A2B',fontWeight:'700'}});