import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { supabase } from '../../../lib/supabase';

type Horse = Record<string, unknown>;
function value(row: Horse, ...keys: string[]) { for (const key of keys) { const v = row[key]; if (typeof v === 'string' && v.trim()) return v.trim(); if (typeof v === 'number') return String(v); } return ''; }
function imageUrl(row: Horse) { const cover = value(row, 'cover_image_url'); if (cover) return cover; const urls = row.image_urls; if (Array.isArray(urls) && typeof urls[0] === 'string') return urls[0]; return ''; }

export default function HorseProfileScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter();
  const [horse, setHorse] = useState<Horse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); const horseId = Array.isArray(id) ? id[0] : id; if (!horseId) { setError('Horse not found.'); setLoading(false); return; } const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError('Please sign in to view this horse.'); setLoading(false); return; } const { data, error: queryError } = await supabase.from('horse_listings').select('*').eq('id', horseId).eq('user_id', user.id).maybeSingle(); if (queryError) setError(queryError.message); else if (!data) setError('Horse not found.'); else setHorse(data as Horse); setLoading(false); }, [id]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" /><Text style={styles.muted}>Loading horse profile…</Text></View>;
  if (!horse) return <SafeAreaView style={styles.safe}><View style={styles.errorPage}><Text style={styles.errorTitle}>Unable to open profile</Text><Text style={styles.errorText}>{error ?? 'Horse not found.'}</Text><Pressable style={styles.button} onPress={() => router.back()}><Text style={styles.buttonText}>Go back</Text></Pressable></View></SafeAreaView>;
  const name = value(horse, 'name', 'horse_name', 'title') || 'Unnamed horse'; const photo = imageUrl(horse);
  const facts = [['Breed', value(horse, 'breed', 'breed_name')], ['Gender', value(horse, 'gender', 'sex')], ['Age', value(horse, 'age', 'years')], ['Height', value(horse, 'height')], ['Color', value(horse, 'color')], ['Discipline', value(horse, 'discipline')], ['Level', value(horse, 'level')], ['Country', value(horse, 'country')]].filter(([, v]) => v);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ My Horses</Text></Pressable>{photo ? <Image source={{ uri: photo }} style={styles.hero} resizeMode="cover" /> : <View style={styles.heroPlaceholder}><Text style={styles.horseEmoji}>🐴</Text></View>}<Text style={styles.name}>{name}</Text><Text style={styles.sub}>{[value(horse, 'breed', 'breed_name'), value(horse, 'gender', 'sex')].filter(Boolean).join(' • ') || 'Horse profile'}</Text><View style={styles.card}><Text style={styles.sectionTitle}>Horse details</Text>{facts.map(([label, fact]) => <View key={label} style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.fact}>{fact}</Text></View>)}</View>{value(horse, 'sire', 'dam', 'dam_sire') ? <View style={styles.card}><Text style={styles.sectionTitle}>Pedigree</Text>{([['Sire', value(horse, 'sire')], ['Dam', value(horse, 'dam')], ['Dam sire', value(horse, 'dam_sire')]] as const).filter(([, v]) => v).map(([label, fact]) => <View key={label} style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.fact}>{fact}</Text></View>)}</View> : null}{value(horse, 'description') ? <View style={styles.card}><Text style={styles.sectionTitle}>About</Text><Text style={styles.description}>{value(horse, 'description')}</Text></View> : null}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F7F5F0' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F7F5F0' }, muted: { marginTop: 10, opacity: 0.55 }, content: { padding: 20, paddingBottom: 50 }, back: { fontSize: 15, fontWeight: '800', color: '#0E5A45', marginBottom: 16 }, hero: { width: '100%', height: 240, borderRadius: 24, backgroundColor: '#EAE7DF' }, heroPlaceholder: { width: '100%', height: 240, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EAE7DF' }, horseEmoji: { fontSize: 72 }, name: { marginTop: 18, fontSize: 30, fontWeight: '900' }, sub: { marginTop: 5, fontSize: 15, opacity: 0.58 }, card: { marginTop: 18, padding: 18, borderRadius: 20, backgroundColor: '#FFFFFF' }, sectionTitle: { fontSize: 18, fontWeight: '900', marginBottom: 8 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 18, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#F0EEE8' }, label: { fontSize: 14, opacity: 0.55 }, fact: { flex: 1, textAlign: 'right', fontSize: 14, fontWeight: '700' }, description: { fontSize: 15, lineHeight: 23, opacity: 0.72 }, errorPage: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30 }, errorTitle: { fontSize: 22, fontWeight: '900' }, errorText: { marginTop: 8, textAlign: 'center', lineHeight: 21, opacity: 0.6 }, button: { marginTop: 20, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 14, backgroundColor: '#0E5A45' }, buttonText: { color: '#FFFFFF', fontWeight: '800' } });
