import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,useLocalSearchParams } from 'expo-router';
import { supabase } from '../../../../lib/supabase';

type Competition={id:string;name:string;venue:string|null;class_name:string|null;discipline:string|null;competition_date:string;horse_id:string|null};
type Horse={id:string;name:string};
type ChecklistRow={id:string;title:string;completed:boolean};
const steps=[['Warm-up','Walk, loosen and follow your trainer’s warm-up plan.'],['Course walk','Review the course, distances, turns and your plan.'],['Final tack check','Check saddle, bridle, girth, boots and competition equipment.'],['Horse check','Water, comfort, shoes and anything your trainer wants checked.'],['Documents','Keep passport, entry confirmation and class details ready.']];
const fmt=(d:string)=>new Date(d).toLocaleDateString(undefined,{weekday:'long',day:'2-digit',month:'long',year:'numeric'});
export default function CompetitionDay(){const{id}=useLocalSearchParams<{id:string}>();const cid=Array.isArray(id)?id[0]:id;const[item,setItem]=useState<Competition|null>(null);const[horse,setHorse]=useState<Horse|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[quick,setQuick]=useState<Record<string,ChecklistRow>>({});const[error,setError]=useState<string|null>(null);
 const load=useCallback(async(pull=false)=>{pull?setRefreshing(true):setLoading(true);setError(null);const{data:{user}}=await supabase.auth.getUser();if(!user||!cid){setError('Competition not found.');setLoading(false);setRefreshing(false);return}const[{data:c,error:ce},{data:h},{data:q,error:qe}]=await Promise.all([supabase.from('competitions').select('id,name,venue,class_name,discipline,competition_date,horse_id').eq('id',cid).eq('user_id',user.id).single(),supabase.from('horse_listings').select('id,name').eq('user_id',user.id),supabase.from('competition_checklist_items').select('id,title,completed').eq('competition_id',cid).eq('user_id',user.id).like('category','Competition Day')]);if(ce||!c){setError(ce?.message??'Competition not found.');setLoading(false);setRefreshing(false);return}if(qe)setError(qe.message);const existing=(q??[]) as ChecklistRow[];const missing=steps.filter(([title])=>!existing.some(x=>x.title===title));let rows=existing;if(missing.length){const inserts=missing.map(([title])=>({user_id:user.id,competition_id:cid,title,category:'Competition Day',sort_order:steps.findIndex(x=>x[0]===title)}));const{data:created,error:ie}=await supabase.from('competition_checklist_items').insert(inserts).select('id,title,completed');if(ie)setError(ie.message);else rows=[...existing,...((created??[]) as ChecklistRow[])]}setItem(c as Competition);setHorse(((h??[]) as Horse[]).find(x=>x.id===c.horse_id)??null);setQuick(Object.fromEntries(rows.map(x=>[x.title,x])));setLoading(false);setRefreshing(false)},[cid]);useEffect(()=>{void load()},[load]);
 async function toggle(title:string){const row=quick[title];if(!row)return;const completed=!row.completed;setQuick(x=>({...x,[title]:{...x[title],completed}}));const{error:e}=await supabase.from('competition_checklist_items').update({completed,completed_at:completed?new Date().toISOString():null}).eq('id',row.id).eq('competition_id',cid);if(e){setQuick(x=>({...x,[title]:{...x[title],completed:!completed}}));setError(e.message)}}
 const event=useMemo(()=>item?new Date(item.competition_date):null,[item]);const now=Date.now();const diff=event?event.getTime()-now:0;const isToday=event?event.toDateString()===new Date(now).toDateString():false;const hours=Math.max(0,Math.floor(diff/3600000));const mins=Math.max(0,Math.floor((diff%3600000)/60000));const completeCount=steps.filter(([title])=>quick[title]?.completed).length;const progress=Math.round(completeCount/steps.length*100);
 if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Loading competition day…</Text></View>;
 if(!item||!event)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.error}>{error??'Competition not found.'}</Text></View></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Competition</Text></Pressable><Text style={styles.brand}>SHABDIZ</Text><Text style={styles.title}>Competition Day</Text><Text style={styles.subtitle}>{item.name}</Text>
 <View style={styles.hero}><Text style={styles.icon}>🏆</Text><Text style={styles.heroTitle}>{isToday?'TODAY IS COMPETITION DAY':diff<0?'Competition day has passed':`${Math.floor(diff/86400000)} days to go`}</Text>{isToday&&diff>0?<Text style={styles.countdown}>{hours}h {mins}m</Text>:null}<Text style={styles.heroDate}>{fmt(item.competition_date)}</Text>{item.venue?<Text style={styles.heroMeta}>📍 {item.venue}</Text>:null}{item.class_name?<Text style={styles.heroMeta}>Class: {item.class_name}</Text>:null}{horse?<Text style={styles.heroMeta}>🐎 {horse.name}</Text>:null}</View>
 <View style={styles.card}><Text style={styles.section}>Quick checklist</Text><Text style={styles.hint}>{completeCount} of {steps.length} completed · {progress}%</Text><View style={styles.track}><View style={[styles.fill,{width:`${progress}%`}]}/></View>{steps.map(([title,text])=>{const checked=Boolean(quick[title]?.completed);return <Pressable key={title} onPress={()=>void toggle(title)} style={styles.row}><View style={[styles.check,checked&&styles.checked]}><Text style={styles.checkText}>{checked?'✓':''}</Text></View><View style={styles.copy}><Text style={[styles.itemTitle,checked&&styles.completed]}>{title}</Text><Text style={styles.itemText}>{text}</Text></View></Pressable>})}</View>
 <View style={styles.card}><Text style={styles.section}>Competition actions</Text><Pressable onPress={()=>router.push(`/(tabs)/competition/checklist/${item.id}`)} style={styles.action}><Text style={styles.actionTitle}>✅ Full preparation checklist</Text><Text style={styles.actionText}>Equipment, transport, documents and final checks.</Text></Pressable><Pressable onPress={()=>router.push(`/(tabs)/reminders`)} style={styles.action}><Text style={styles.actionTitle}>🔔 Open reminders</Text><Text style={styles.actionText}>Review today’s competition preparation reminders.</Text></Pressable><Pressable onPress={()=>router.push(`/(tabs)/competition/${item.id}`)} style={styles.action}><Text style={styles.actionTitle}>📝 Record result</Text><Text style={styles.actionText}>Enter rank, score, faults and performance notes after the show.</Text></Pressable></View>
 <View style={styles.note}><Text style={styles.noteTitle}>🏇 Competition day note</Text><Text style={styles.noteText}>Your quick checklist is saved to the competition, so progress remains after leaving this screen. Follow your trainer’s competition plan and your veterinarian’s advice where relevant.</Text></View>{error?<Text style={styles.error}>{error}</Text>:null}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F5F0'},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F5F0',padding:24},back:{color:'#0E5A45',fontWeight:'800',marginBottom:14},brand:{fontSize:30,fontWeight:'900',letterSpacing:2.5,color:'#0E5A45'},title:{marginTop:14,fontSize:30,fontWeight:'900'},subtitle:{marginTop:5,fontSize:15,fontWeight:'700',opacity:.6},hero:{marginTop:18,padding:22,borderRadius:22,backgroundColor:'#123F31'},icon:{fontSize:36},heroTitle:{marginTop:8,fontSize:21,fontWeight:'900',color:'#FFF'},countdown:{marginTop:8,fontSize:30,fontWeight:'900',color:'#FFF'},heroDate:{marginTop:10,fontSize:13,fontWeight:'800',color:'#DCEBE5'},heroMeta:{marginTop:5,fontSize:13,fontWeight:'700',color:'#DCEBE5'},card:{marginTop:16,padding:18,borderRadius:22,backgroundColor:'#FFF'},section:{fontSize:20,fontWeight:'900'},hint:{marginTop:5,fontSize:12,opacity:.55},track:{marginTop:12,height:8,borderRadius:5,backgroundColor:'#E3E1DA',overflow:'hidden'},fill:{height:8,backgroundColor:'#0E5A45'},row:{marginTop:12,paddingTop:12,borderTopWidth:1,borderTopColor:'#F0EEE8',flexDirection:'row',alignItems:'center'},check:{width:28,height:28,borderRadius:9,borderWidth:2,borderColor:'#C8CBC7',alignItems:'center',justifyContent:'center',marginRight:12},checked:{backgroundColor:'#0E5A45',borderColor:'#0E5A45'},checkText:{color:'#FFF',fontWeight:'900'},copy:{flex:1},itemTitle:{fontSize:15,fontWeight:'900'},completed:{textDecorationLine:'line-through',opacity:.45},itemText:{marginTop:3,fontSize:12,lineHeight:17,opacity:.6},action:{marginTop:12,padding:15,borderRadius:16,backgroundColor:'#F7F5F0'},actionTitle:{fontSize:15,fontWeight:'900',color:'#0E5A45'},actionText:{marginTop:4,fontSize:12,lineHeight:17,opacity:.6},note:{marginTop:16,padding:16,borderRadius:18,backgroundColor:'#E9F3EE'},noteTitle:{fontSize:15,fontWeight:'900',color:'#0E5A45'},noteText:{marginTop:6,fontSize:12,lineHeight:18,color:'#456259'},muted:{marginTop:7,opacity:.55},error:{marginTop:12,color:'#A33A2B',fontWeight:'700'}});