import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,useLocalSearchParams } from 'expo-router';
import { supabase } from '../../../../lib/supabase';

type Horse={id:string;name:string;breed:string|null;gender:string|null;age:number|null;height:number|null;color:string|null;discipline:string|null;level:string|null;cover_image_url:string|null};
type Training={training_date:string;discipline:string;rating:number|null;duration_minutes:number|null};
type Health={record_date:string;record_type:string;title:string};
type Reminder={id:string;due_at:string;title:string;reminder_type:string};
type Competition={id:string;name:string;competition_date:string;status:string;class_name:string|null;result_rank:number|null;score:number|null;faults:number|null};
const fmt=(d?:string|null)=>d?new Date(d).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';
const ago=(d?:string|null)=>{if(!d)return 'No activity';const n=Math.max(0,Math.floor((Date.now()-new Date(d).getTime())/86400000));return n===0?'Today':`${n} day${n===1?'':'s'} ago`};
export default function Horse360(){const{horseId}=useLocalSearchParams<{horseId:string}>();const[horse,setHorse]=useState<Horse|null>(null);const[training,setTraining]=useState<Training[]>([]);const[health,setHealth]=useState<Health[]>([]);const[reminders,setReminders]=useState<Reminder[]>([]);const[competitions,setCompetitions]=useState<Competition[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState<string|null>(null);
const load=useCallback(async(pull=false)=>{if(pull)setRefreshing(true);else setLoading(true);setError(null);const{data:{user}}=await supabase.auth.getUser();if(!user||!horseId){setError('Horse not found.');setLoading(false);setRefreshing(false);return}const[{data:h,error:he},{data:t,error:te},{data:hr,error:hre},{data:r,error:re},{data:c,error:ce}]=await Promise.all([supabase.from('horse_listings').select('id,name,breed,gender,age,height,color,discipline,level,cover_image_url').eq('id',horseId).eq('user_id',user.id).single(),supabase.from('training_sessions').select('training_date,discipline,rating,duration_minutes').eq('horse_id',horseId).eq('user_id',user.id).order('training_date',{ascending:false}).limit(100),supabase.from('horse_health_records').select('record_date,record_type,title').eq('horse_id',horseId).eq('user_id',user.id).order('record_date',{ascending:false}).limit(100),supabase.from('reminders').select('id,due_at,title,reminder_type').eq('horse_id',horseId).eq('user_id',user.id).eq('status','pending').eq('enabled',true).order('due_at',{ascending:true}).limit(50),supabase.from('competitions').select('id,name,competition_date,status,class_name,result_rank,score,faults').eq('horse_id',horseId).eq('user_id',user.id).order('competition_date',{ascending:false}).limit(100)]);const e=he??te??hre??re??ce;if(e)setError(e.message);setHorse(h as Horse);setTraining((t??[]) as Training[]);setHealth((hr??[]) as Health[]);setReminders((r??[]) as Reminder[]);setCompetitions((c??[]) as Competition[]);setLoading(false);setRefreshing(false)},[horseId]);useEffect(()=>{void load()},[load]);
const metrics=useMemo(()=>{const ratings=training.map(x=>x.rating).filter((x):x is number=>x!=null);const completed=competitions.filter(x=>x.status==='completed');const ranked=completed.filter(x=>x.result_rank!=null);const future=competitions.filter(x=>x.status==='planned'&&new Date(x.competition_date).getTime()>=Date.now()).sort((a,b)=>new Date(a.competition_date).getTime()-new Date(b.competition_date).getTime())[0]??null;const nextReminder=reminders.find(x=>new Date(x.due_at).getTime()>=Date.now())??null;const last=[training[0]?.training_date,health[0]?.record_date,competitions[0]?.competition_date].filter(Boolean).sort((a,b)=>new Date(b!).getTime()-new Date(a!).getTime())[0]??null;return{avg:ratings.length?ratings.reduce((a,b)=>a+b,0)/ratings.length:null,completed:completed.length,ranked:ranked.length,best:ranked.length?Math.min(...ranked.map(x=>x.result_rank!)):null,future,nextReminder,last}},[training,health,competitions,reminders]);
if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Loading Horse 360°…</Text></View>;if(!horse)return <SafeAreaView style={styles.safe}><View style={styles.content}><Text style={styles.error}>{error??'Horse not found.'}</Text><Pressable onPress={()=>router.back()} style={styles.primary}><Text style={styles.primaryText}>Back</Text></Pressable></View></SafeAreaView>;
return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Horse Profile</Text></Pressable><Text style={styles.eyebrow}>SHABDIZ · HORSE 360°</Text><Text style={styles.title}>{horse.name}</Text><Text style={styles.subtitle}>{[horse.breed,horse.discipline,horse.level].filter(Boolean).join(' · ')||'Complete horse overview'}</Text>{error?<Text style={styles.error}>{error}</Text>:null}
<View style={styles.hero}><Text style={styles.heroTitle}>🐎 {horse.name}</Text><Text style={styles.heroText}>{metrics.last?`Last activity ${ago(metrics.last)} · ${fmt(metrics.last)}`:'No recorded activity yet.'}</Text><View style={styles.heroGrid}><Mini value={String(training.length)} label="Training"/><Mini value={String(health.length)} label="Health"/><Mini value={String(competitions.length)} label="Shows"/><Mini value={String(reminders.length)} label="Open tasks"/></View></View>
<View style={styles.card}><Text style={styles.section}>📊 Performance</Text><View style={styles.stats}><Stat value={metrics.avg==null?'—':`${metrics.avg.toFixed(1)}/10`} label="Training avg"/><Stat value={String(metrics.completed)} label="Completed shows"/><Stat value={metrics.best==null?'—':`#${metrics.best}`} label="Best rank"/><Stat value={String(metrics.ranked)} label="Ranked shows"/></View><Pressable onPress={()=>router.push(`/(tabs)/horse/performance/${horse.id}`)} style={styles.action}><Text style={styles.actionText}>Open detailed performance ›</Text></Pressable></View>
<View style={styles.card}><Text style={styles.section}>🏇 Training</Text>{training.length?training.slice(0,4).map((x,i)=><View key={`${x.training_date}-${i}`} style={styles.row}><View style={styles.rowMain}><Text style={styles.rowTitle}>{x.discipline||'Training session'}</Text><Text style={styles.rowMeta}>{fmt(x.training_date)}{x.duration_minutes?` · ${x.duration_minutes} min`:''}</Text></View><Text style={styles.value}>{x.rating==null?'—':`${x.rating}/10`}</Text></View>):<Text style={styles.emptyText}>No training sessions recorded.</Text>}<Pressable onPress={()=>router.push(`/(tabs)/training?horseId=${horse.id}`)} style={styles.action}><Text style={styles.actionText}>Open Training Center ›</Text></Pressable></View>
<View style={styles.card}><Text style={styles.section}>🩺 Health & Care</Text>{health.length?health.slice(0,4).map((x,i)=><View key={`${x.record_date}-${i}`} style={styles.row}><View style={styles.rowMain}><Text style={styles.rowTitle}>{x.title}</Text><Text style={styles.rowMeta}>{x.record_type} · {fmt(x.record_date)}</Text></View></View>):<Text style={styles.emptyText}>No health records recorded.</Text>}<Pressable onPress={()=>router.push(`/(tabs)/health/${horse.id}`)} style={styles.action}><Text style={styles.actionText}>Open Health Records ›</Text></Pressable></View>
<View style={styles.card}><Text style={styles.section}>🔔 Upcoming tasks</Text>{metrics.nextReminder?<View style={styles.next}><Text style={styles.nextTitle}>{metrics.nextReminder.title}</Text><Text style={styles.rowMeta}>{fmt(metrics.nextReminder.due_at)} · {metrics.nextReminder.reminder_type}</Text></View>:<Text style={styles.emptyText}>No open care reminders.</Text>}<Pressable onPress={()=>router.push('/(tabs)/reminders')} style={styles.action}><Text style={styles.actionText}>Open Reminders ›</Text></Pressable></View>
<View style={styles.card}><Text style={styles.section}>🏆 Competitions</Text>{metrics.future?<View style={styles.next}><Text style={styles.nextTitle}>{metrics.future.name}</Text><Text style={styles.rowMeta}>{fmt(metrics.future.competition_date)}{metrics.future.class_name?` · ${metrics.future.class_name}`:''}</Text></View>:null}{competitions.slice(0,4).map(x=><Pressable key={x.id} onPress={()=>router.push(`/(tabs)/competition/${x.id}`)} style={styles.row}><View style={styles.rowMain}><Text style={styles.rowTitle}>{x.name}</Text><Text style={styles.rowMeta}>{fmt(x.competition_date)} · {x.status}</Text></View><Text style={styles.value}>{x.result_rank?`#${x.result_rank}`:x.score!=null?`${x.score}`:'›'}</Text></Pressable>)}{!competitions.length?<Text style={styles.emptyText}>No competitions recorded.</Text>:null}<Pressable onPress={()=>router.push('/(tabs)/competitions')} style={styles.action}><Text style={styles.actionText}>Open Competitions ›</Text></Pressable></View>
<View style={styles.card}><Text style={styles.section}>⚡ Quick actions</Text><View style={styles.quick}><Pressable onPress={()=>router.push(`/(tabs)/training?horseId=${horse.id}`)} style={styles.quickButton}><Text style={styles.quickText}>🏇 Train</Text></Pressable><Pressable onPress={()=>router.push(`/(tabs)/health/${horse.id}`)} style={styles.quickButton}><Text style={styles.quickText}>🩺 Health</Text></Pressable><Pressable onPress={()=>router.push(`/(tabs)/add-reminder?horseId=${horse.id}`)} style={styles.quickButton}><Text style={styles.quickText}>🔔 Reminder</Text></Pressable></View></View>
<View style={styles.note}><Text style={styles.noteTitle}>Horse 360°</Text><Text style={styles.noteText}>A consolidated view of your recorded horse data. Performance and readiness summaries are descriptive and should be used together with your trainer and veterinary advice.</Text></View></ScrollView></SafeAreaView>}
function Mini({value,label}:{value:string;label:string}){return <View><Text style={styles.miniValue}>{value}</Text><Text style={styles.miniLabel}>{label}</Text></View>}function Stat({value,label}:{value:string;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F5F0'},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F5F0'},back:{color:'#0E5A45',fontWeight:'800',marginBottom:16},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#0E5A45'},title:{marginTop:7,fontSize:32,fontWeight:'900'},subtitle:{marginTop:4,fontSize:13,opacity:.55},hero:{marginTop:18,padding:19,borderRadius:22,backgroundColor:'#123F31'},heroTitle:{fontSize:22,fontWeight:'900',color:'#FFF'},heroText:{marginTop:6,fontSize:12,color:'#DCEBE5'},heroGrid:{marginTop:18,flexDirection:'row',justifyContent:'space-between'},miniValue:{fontSize:21,fontWeight:'900',color:'#FFF'},miniLabel:{marginTop:3,fontSize:9,fontWeight:'800',color:'#DCEBE5'},card:{marginTop:16,padding:18,borderRadius:21,backgroundColor:'#FFF'},section:{fontSize:19,fontWeight:'900',marginBottom:12},stats:{flexDirection:'row',flexWrap:'wrap',gap:8},stat:{width:'47%',padding:12,borderRadius:14,backgroundColor:'#F7F5F0'},statValue:{fontSize:20,fontWeight:'900',color:'#0E5A45'},statLabel:{marginTop:3,fontSize:10,fontWeight:'700',opacity:.55},row:{minHeight:55,borderTopWidth:1,borderTopColor:'#EEECE6',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},rowMain:{flex:1,paddingRight:10},rowTitle:{fontSize:14,fontWeight:'900'},rowMeta:{marginTop:3,fontSize:11,opacity:.55},value:{fontWeight:'900',color:'#0E5A45'},next:{padding:13,borderRadius:14,backgroundColor:'#E9F3EE',marginBottom:5},nextTitle:{fontSize:14,fontWeight:'900',color:'#173C31'},action:{marginTop:12,minHeight:44,borderRadius:13,backgroundColor:'#E9F3EE',alignItems:'center',justifyContent:'center'},actionText:{fontWeight:'900',color:'#0E5A45'},quick:{flexDirection:'row',gap:8},quickButton:{flex:1,minHeight:44,borderRadius:13,backgroundColor:'#F7F5F0',alignItems:'center',justifyContent:'center'},quickText:{fontSize:11,fontWeight:'900',color:'#0E5A45'},emptyText:{fontSize:13,opacity:.55,lineHeight:20},note:{marginTop:16,padding:16,borderRadius:18,backgroundColor:'#EDEBE4'},noteTitle:{fontWeight:'900',color:'#0E5A45'},noteText:{marginTop:5,fontSize:11,lineHeight:17,opacity:.62},muted:{marginTop:6,opacity:.55},error:{marginTop:12,color:'#A33A2B',fontWeight:'700'}});