import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '../../lib/supabase';

type Reminder={id:string;title:string;reminder_type:string;due_at:string;horse_id:string|null;horse_name?:string|null;};
type ArrayItem=Date|null;
const C={green:'#174D3F',greenDark:'#103D32',gold:'#D9A93A',cream:'#F7F5F0',white:'#FFFFFF',muted:'#7B817D',line:'#E4E0D7',soft:'#EAF2EE'};
const WEEK=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
function key(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function monthStart(date:Date){return new Date(date.getFullYear(),date.getMonth(),1);}
function monthEnd(date:Date){return new Date(date.getFullYear(),date.getMonth()+1,0);}
function shiftMonth(date:Date,delta:number){return new Date(date.getFullYear(),date.getMonth()+delta,1);}

export default function CalendarScreen(){
 const[today]=useState(new Date());const[month,setMonth]=useState(monthStart(new Date()));const[items,setItems]=useState<Reminder[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');const start=new Date(month.getFullYear(),month.getMonth(),1);const end=new Date(month.getFullYear(),month.getMonth()+1,1);const{data,error:e}=await supabase.from('reminders').select('id,title,reminder_type,due_at,horse_id').eq('status','pending').eq('enabled',true).gte('due_at',start.toISOString()).lt('due_at',end.toISOString()).order('due_at',{ascending:true});if(e){setError(e.message);setItems([]);setLoading(false);return;}const reminders=(data??[]) as Reminder[];const ids=[...new Set(reminders.map(r=>r.horse_id).filter(Boolean))] as string[];if(ids.length){const[{data:personal},{data:listings}]=await Promise.all([supabase.from('personal_horses').select('id,name').in('id',ids),supabase.from('horse_listings').select('id,name').in('id',ids)]);const names=new Map<string,string>();for(const h of personal??[])names.set(h.id,h.name);for(const h of listings??[])names.set(h.id,h.name);for(const r of reminders)r.horse_name=r.horse_id?names.get(r.horse_id)??null:null;}setItems(reminders);setLoading(false);},[month]);
 useEffect(()=>{void load();},[load]);
 const byDay=useMemo(()=>{const m=new Map<string,Reminder[]>();for(const item of items){const k=key(new Date(item.due_at));const list=m.get(k)??[];list.push(item);m.set(k,list);}return m;},[items]);
 const cells=useMemo(()=>{const first=monthStart(month);const last=monthEnd(month);const offset=(first.getDay()+6)%7;const arr:ArrayItem[]=[];for(let i=0;i<offset;i++)arr.push(null);for(let day=1;day<=last.getDate();day++)arr.push(new Date(month.getFullYear(),month.getMonth(),day));while(arr.length%7)arr.push(null);return arr;},[month]);
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><View style={styles.headerCopy}><Text style={styles.kicker}>EQUIMASTER PRO</Text><Text style={styles.title}>Calendar</Text><Text style={styles.subtitle}>Your reminders, organized by day.</Text></View><Pressable style={styles.todayButton} onPress={()=>setMonth(monthStart(today))}><Text style={styles.todayText}>Today</Text></Pressable></View>
 <View style={styles.monthBar}><Pressable style={styles.nav} onPress={()=>setMonth(m=>shiftMonth(m,-1))}><Text style={styles.navText}>‹</Text></Pressable><Text style={styles.monthTitle}>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Pressable style={styles.nav} onPress={()=>setMonth(m=>shiftMonth(m,1))}><Text style={styles.navText}>›</Text></Pressable></View>
 <View style={styles.weekRow}>{WEEK.map(d=><Text key={d} style={styles.week}>{d}</Text>)}</View>
 <View style={styles.grid}>{cells.map((date,i)=>{const selected=date&&key(date)===key(today);const dayItems=date?byDay.get(key(date))??[]:[];return <View key={i} style={[styles.cell,!date&&styles.blank,selected&&styles.selected]}>{date?<><Text style={[styles.day,selected&&styles.selectedDay]}>{date.getDate()}</Text>{dayItems.slice(0,2).map(r=><Pressable key={r.id} onPress={()=>router.push({pathname:'/reminder/[id]',params:{id:r.id}})} style={styles.dotItem}><Text numberOfLines={1} style={styles.dotText}>{r.title}</Text></Pressable>)}{dayItems.length>2?<Text style={styles.more}>+{dayItems.length-2} more</Text>:null}</>:null}</View>;})}</View>
 {error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}{loading?<View style={styles.loading}><ActivityIndicator color={C.green}/><Text style={styles.muted}>Loading calendar…</Text></View>:null}
 {!loading&&items.length===0&&!error?<View style={styles.empty}><Text style={styles.icon}>📅</Text><Text style={styles.emptyTitle}>No reminders this month</Text><Text style={styles.muted}>Create a reminder and it will appear here automatically.</Text><Pressable style={styles.create} onPress={()=>router.push('/add-reminder')}><Text style={styles.createText}>+ Add reminder</Text></Pressable></View>:null}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.cream},container:{padding:20,paddingBottom:40},header:{flexDirection:'row',justifyContent:'space-between',gap:12},headerCopy:{flex:1},kicker:{marginTop:2,color:C.gold,fontSize:11,fontWeight:'900',letterSpacing:2},title:{marginTop:7,color:C.green,fontSize:32,fontWeight:'900'},subtitle:{marginTop:7,color:C.muted,fontSize:14,lineHeight:20},todayButton:{alignSelf:'center',paddingHorizontal:14,paddingVertical:10,borderRadius:12,backgroundColor:C.soft},todayText:{color:C.green,fontSize:13,fontWeight:'900'},monthBar:{marginTop:22,paddingVertical:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},monthTitle:{color:C.green,fontSize:20,fontWeight:'900'},nav:{width:42,height:42,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:C.white},navText:{color:C.green,fontSize:28,lineHeight:30},weekRow:{marginTop:5,flexDirection:'row'},week:{width:'14.2857%',textAlign:'center',fontSize:11,fontWeight:'800',color:C.muted},grid:{marginTop:7,flexDirection:'row',flexWrap:'wrap',borderTopWidth:1,borderLeftWidth:1,borderColor:C.line,borderRadius:16,overflow:'hidden'},cell:{width:'14.2857%',minHeight:82,padding:6,borderRightWidth:1,borderBottomWidth:1,borderColor:C.line,backgroundColor:C.white},blank:{backgroundColor:'#F1EFE9'},selected:{backgroundColor:C.soft},day:{fontSize:13,fontWeight:'800',color:C.green},selectedDay:{color:C.greenDark},dotItem:{marginTop:5,paddingHorizontal:4,paddingVertical:3,borderRadius:5,backgroundColor:C.gold},dotText:{fontSize:9,fontWeight:'800',color:C.greenDark},more:{marginTop:3,fontSize:9,fontWeight:'800',color:C.muted},loading:{marginTop:18,alignItems:'center'},muted:{marginTop:7,textAlign:'center',color:C.muted,fontSize:13,lineHeight:19},empty:{marginTop:18,padding:24,borderRadius:20,backgroundColor:C.white,alignItems:'center'},icon:{fontSize:34},emptyTitle:{marginTop:10,color:C.green,fontSize:18,fontWeight:'900'},create:{marginTop:16,paddingHorizontal:18,paddingVertical:11,borderRadius:13,backgroundColor:C.green},createText:{color:C.white,fontSize:13,fontWeight:'900'},error:{marginTop:16,padding:13,borderRadius:13,backgroundColor:'#F6E9E6'},errorText:{color:'#A33A2B',fontSize:13,lineHeight:19}});
