import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { syncReminderNotifications } from '../../lib/notifications';

type Reminder={id:string;title:string;description:string|null;reminder_type:string;due_at:string;remind_before_minutes:number;horse_id:string|null;competition_id?:string|null};
type Training={id:string;discipline:string;training_date:string;duration_minutes:number|null;horse_id:string};
type Competition={id:string;name:string;competition_date:string;venue:string|null;class_name:string|null;discipline:string|null;horse_id:string|null;notes:string|null};
type Horse={id:string;name:string};
type Event={id:string;title:string;description:string|null;type:string;date:string;horseName:string|null;horseId:string|null;source:'Reminder'|'Training'|'Competition';competitionId:string|null};
const TYPES=['All','Veterinary','Vaccination','Farrier','Training','Competition','Other'];
function dayKey(d:Date){return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`}
function labelType(t:string){return t.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
export default function CalendarScreen(){
 const[reminders,setReminders]=useState<Reminder[]>([]);const[training,setTraining]=useState<Training[]>([]);const[competitions,setCompetitions]=useState<Competition[]>([]);const[horses,setHorses]=useState<Horse[]>([]);const[selectedDay,setSelectedDay]=useState(dayKey(new Date()));const[typeFilter,setTypeFilter]=useState('All');const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async(pull=false)=>{pull?setRefreshing(true):setLoading(true);setError(null);const{data:{user}}=await supabase.auth.getUser();if(!user){setError('Please sign in to use Calendar.');setLoading(false);setRefreshing(false);return}const now=new Date().toISOString();const[{data:r,error:re},{data:t,error:te},{data:c,error:ce},{data:h}]=await Promise.all([supabase.from('reminders').select('id,title,description,reminder_type,due_at,remind_before_minutes,horse_id,competition_id').eq('user_id',user.id).eq('status','pending').eq('enabled',true).gte('due_at',now).order('due_at'),supabase.from('training_sessions').select('id,discipline,training_date,duration_minutes,horse_id').eq('user_id',user.id).gte('training_date',now).order('training_date').limit(50),supabase.from('competitions').select('id,name,competition_date,venue,class_name,discipline,horse_id,notes').eq('user_id',user.id).eq('status','planned').gte('competition_date',now).order('competition_date').limit(50),supabase.from('horse_listings').select('id,name').eq('user_id',user.id)]);if(re||te||ce)setError(re?.message??te?.message??ce?.message??'Could not load calendar.');setReminders((r??[]) as Reminder[]);setTraining((t??[]) as Training[]);setCompetitions((c??[]) as Competition[]);setHorses((h??[]) as Horse[]);try{await syncReminderNotifications((r??[]) as Reminder[])}catch{}setLoading(false);setRefreshing(false)},[]);
 useEffect(()=>{void load()},[load]);
 const horseName=useMemo(()=>new Map(horses.map(h=>[h.id,h.name])),[horses]);
 const events=useMemo<Event[]>(()=>[...reminders.map(r=>({id:`r-${r.id}`,title:r.title,description:r.description,type:r.reminder_type,date:r.due_at,horseName:r.horse_id?horseName.get(r.horse_id)??null:null,horseId:r.horse_id,source:'Reminder' as const,competitionId:r.competition_id??null})),...training.map(t=>({id:`t-${t.id}`,title:`${t.discipline} training`,description:t.duration_minutes?`${t.duration_minutes} min session`:null,type:'training',date:t.training_date,horseName:horseName.get(t.horse_id)??null,horseId:t.horse_id,source:'Training' as const,competitionId:null})),...competitions.map(c=>({id:`c-${c.id}`,title:c.name,description:[c.venue,c.class_name].filter(Boolean).join(' • ')||c.notes,type:'competition',date:c.competition_date,horseName:c.horse_id?horseName.get(c.horse_id)??null:null,horseId:c.horse_id,source:'Competition' as const,competitionId:c.id}))].sort((a,b)=>new Date(a.date).getTime()-new Date(b.date).getTime()),[reminders,training,competitions,horseName]);
 const days=useMemo(()=>{const out:Date[]=[];const now=new Date();for(let i=0;i<14;i++){const d=new Date(now);d.setHours(12,0,0,0);d.setDate(now.getDate()+i);out.push(d)}return out},[]);
 const filtered=events.filter(e=>dayKey(new Date(e.date))===selectedDay&&(typeFilter==='All'||labelType(e.type)===typeFilter));
 const selectedDate=useMemo(()=>{const [year,month,day]=selectedDay.split('-').map(Number);return new Date(year,month,day)},[selectedDay]);
 if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Loading calendar…</Text></View>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>}>
  <View style={styles.headerRow}><View style={styles.headerCopy}><Text style={styles.eyebrow}>SHABDIZ</Text><Text style={styles.title}>Calendar</Text><Text style={styles.subtitle}>Every care task, training session and competition in one place.</Text></View><Pressable onPress={()=>router.push('/(tabs)/add-reminder')} style={styles.add}><Text style={styles.addText}>＋ Add</Text></Pressable></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.days}>{days.map(d=>{const key=dayKey(d);const active=key===selectedDay;const count=events.filter(e=>dayKey(new Date(e.date))===key).length;return <Pressable key={key} onPress={()=>setSelectedDay(key)} style={[styles.dayCard,active&&styles.dayActive]}><Text style={[styles.weekday,active&&styles.activeText]}>{d.toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()}</Text><Text style={[styles.dayNumber,active&&styles.activeText]}>{d.getDate()}</Text>{count>0?<View style={[styles.dot,active&&styles.dotActive]}/>:null}</Pressable>})}</ScrollView>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{TYPES.map(t=><Pressable key={t} onPress={()=>setTypeFilter(t)} style={[styles.filter,typeFilter===t&&styles.filterActive]}><Text style={[styles.filterText,typeFilter===t&&styles.activeText]}>{t}</Text></Pressable>)}</ScrollView>
  <View style={styles.selected}><Text style={styles.selectedKicker}>SELECTED DAY</Text><Text style={styles.selectedDate}>{selectedDate.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</Text><Text style={styles.count}>{filtered.length} {filtered.length===1?'item':'items'}</Text></View>
  {error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}<Text style={styles.section}>Schedule</Text>
  {filtered.length===0?<View style={styles.empty}><Text style={styles.icon}>🐎</Text><Text style={styles.emptyTitle}>Nothing scheduled</Text><Text style={styles.emptyBody}>No care, training or competition items match this day and filter.</Text><Pressable onPress={()=>router.push('/(tabs)/add-reminder')} style={styles.emptyButton}><Text style={styles.emptyButtonText}>＋ Add reminder</Text></Pressable></View>:<View style={styles.list}>{filtered.map(e=><CalendarItem key={e.id} event={e}/>)}</View>}
 </ScrollView></SafeAreaView>
}
function CalendarItem({event}:{event:Event}){const date=new Date(event.date);const isCompetition=event.source==='Competition';const isCompetitionReminder=event.source==='Reminder'&&Boolean(event.competitionId);return <Pressable onPress={()=>isCompetition?router.push(`/(tabs)/competition/day/${event.competitionId??event.id.slice(2)}`):isCompetitionReminder?router.push(`/(tabs)/competition/day/${event.competitionId}`):event.source==='Reminder'?router.push(`/(tabs)/reminder/${event.id.slice(2)}`):router.push(`/(tabs)/training?horseId=${event.horseId??''}`)} style={styles.item}><View style={styles.timeBox}><Text style={styles.time}>{date.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</Text><Text style={styles.source}>{isCompetition||isCompetitionReminder?'Competition Day':event.source}</Text></View><View style={styles.copy}><Text style={styles.itemTitle}>{event.title}</Text><Text style={styles.meta}>{labelType(event.type)}{event.horseName?` • ${event.horseName}`:''}</Text>{event.description?<Text style={styles.body}>{event.description}</Text>:null}{isCompetition||isCompetitionReminder?<Text style={styles.dayLink}>🏆 Open Competition Day ›</Text>:null}</View></Pressable>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F5F0'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F5F0'},container:{padding:20,paddingBottom:50},headerRow:{flexDirection:'row',justifyContent:'space-between',gap:12},headerCopy:{flex:1},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:2,opacity:.55},title:{marginTop:10,fontSize:32,fontWeight:'900'},subtitle:{marginTop:6,fontSize:15,lineHeight:21,opacity:.58},add:{marginTop:4,paddingHorizontal:14,minHeight:40,borderRadius:13,backgroundColor:'#0E5A45',alignItems:'center',justifyContent:'center'},addText:{color:'#FFF',fontWeight:'900'},days:{gap:8,paddingVertical:18},dayCard:{width:58,height:76,borderRadius:16,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center'},dayActive:{backgroundColor:'#0E5A45'},weekday:{fontSize:9,fontWeight:'900',opacity:.5},dayNumber:{marginTop:5,fontSize:22,fontWeight:'900'},activeText:{color:'#FFF',opacity:1},dot:{marginTop:5,width:5,height:5,borderRadius:3,backgroundColor:'#0E5A45'},dotActive:{backgroundColor:'#FFF'},filters:{gap:8,paddingBottom:18},filter:{paddingHorizontal:13,paddingVertical:9,borderRadius:16,backgroundColor:'#EAE8E1'},filterActive:{backgroundColor:'#0E5A45'},filterText:{fontSize:12,fontWeight:'800',color:'#555C58'},selected:{padding:18,borderRadius:20,backgroundColor:'#0E5A45'},selectedKicker:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:'#DCEBE5'},selectedDate:{marginTop:7,fontSize:19,fontWeight:'900',color:'#FFF'},count:{marginTop:6,color:'#DCEBE5',fontWeight:'700'},section:{marginTop:26,marginBottom:12,fontSize:21,fontWeight:'900'},list:{gap:10},item:{padding:15,borderRadius:19,backgroundColor:'#FFF',flexDirection:'row',gap:14},timeBox:{width:82},time:{fontSize:16,fontWeight:'900',color:'#0E5A45'},source:{marginTop:4,fontSize:10,fontWeight:'800',opacity:.45},copy:{flex:1},itemTitle:{fontSize:16,fontWeight:'900'},meta:{marginTop:5,fontSize:12,fontWeight:'800',color:'#0E5A45',textTransform:'capitalize'},body:{marginTop:4,fontSize:13,lineHeight:19,opacity:.6},dayLink:{marginTop:8,fontSize:12,fontWeight:'900',color:'#0E5A45'},empty:{padding:28,borderRadius:20,backgroundColor:'#FFF',alignItems:'center'},icon:{fontSize:40},emptyTitle:{marginTop:10,fontSize:19,fontWeight:'900'},emptyBody:{marginTop:6,textAlign:'center',lineHeight:20,opacity:.58},emptyButton:{marginTop:16,paddingHorizontal:16,paddingVertical:11,borderRadius:13,backgroundColor:'#E9F3EE'},emptyButtonText:{color:'#0E5A45',fontWeight:'900'},error:{marginTop:16,padding:12,borderRadius:13,backgroundColor:'#FCECEC'},errorText:{color:'#8C2F2F',fontSize:13},muted:{marginTop:8,opacity:.55}});