import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '../../lib/supabase';

type Horse={id:string;name:string};
type Competition={id:string;name:string;competition_date:string;discipline:string|null;class_name:string|null;venue:string|null;horse_id:string|null;status:string;result_rank:number|null;score:number|null;faults:number|null};
type Stat={horse:Horse;starts:number;completed:number;cancelled:number;ranked:number;bestRank:number|null;avgRank:number|null;totalFaults:number;avgScore:number|null;results:Competition[]};

export default function CompetitionStatsScreen(){
 const[horses,setHorses]=useState<Horse[]>([]);const[items,setItems]=useState<Competition[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async(pull=false)=>{pull?setRefreshing(true):setLoading(true);setError(null);const{data:{user}}=await supabase.auth.getUser();if(!user){setError('Please sign in first.');setLoading(false);setRefreshing(false);return}const[{data:c,error:e},{data:h}]=await Promise.all([supabase.from('competitions').select('id,name,competition_date,discipline,class_name,venue,horse_id,status,result_rank,score,faults').eq('user_id',user.id).not('horse_id','is',null).order('competition_date',{ascending:false}).limit(200),supabase.from('horse_listings').select('id,name').eq('user_id',user.id).order('name')]);if(e)setError(e.message);setItems((c??[]) as Competition[]);setHorses((h??[]) as Horse[]);setLoading(false);setRefreshing(false)},[]);
 useEffect(()=>{void load()},[load]);
 const stats=useMemo<Stat[]>(()=>horses.map(h=>{const rows=items.filter(c=>c.horse_id===h.id);const completed=rows.filter(c=>c.status==='completed');const ranked=completed.filter(c=>c.result_rank!=null);const ranks=ranked.map(c=>c.result_rank as number);const scores=completed.filter(c=>c.score!=null).map(c=>c.score as number);return{horse:h,starts:rows.length,completed:completed.length,cancelled:rows.filter(c=>c.status==='cancelled').length,ranked:ranked.length,bestRank:ranks.length?Math.min(...ranks):null,avgRank:ranks.length?ranks.reduce((a,b)=>a+b,0)/ranks.length:null,totalFaults:completed.reduce((a,c)=>a+(c.faults??0),0),avgScore:scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:null,results:completed.slice(0,5)} }).filter(s=>s.starts>0),[horses,items]);
 const overall=useMemo(()=>({starts:items.length,completed:items.filter(c=>c.status==='completed').length,totalFaults:items.filter(c=>c.status==='completed').reduce((a,c)=>a+(c.faults??0),0),ranked:items.filter(c=>c.status==='completed'&&c.result_rank!=null).length}),[items]);
 if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Loading competition statistics…</Text></View>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.brand}>SHABDIZ</Text><Text style={styles.title}>Competition Stats</Text><Text style={styles.subtitle}>Track starts, results, faults and scoring for each horse.</Text>{error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}
 <View style={styles.overview}><View><Text style={styles.overValue}>{overall.starts}</Text><Text style={styles.overLabel}>Starts</Text></View><View><Text style={styles.overValue}>{overall.completed}</Text><Text style={styles.overLabel}>Completed</Text></View><View><Text style={styles.overValue}>{overall.ranked}</Text><Text style={styles.overLabel}>Ranked</Text></View><View><Text style={styles.overValue}>{overall.totalFaults}</Text><Text style={styles.overLabel}>Faults</Text></View></View>
 {stats.length===0?<View style={styles.empty}><Text style={styles.icon}>📊</Text><Text style={styles.emptyTitle}>No competition results yet</Text><Text style={styles.emptyBody}>Assign a horse to a competition and record its result to build performance statistics.</Text><Pressable style={styles.primary} onPress={()=>router.push('/(tabs)/competitions')}><Text style={styles.primaryText}>Manage competitions</Text></Pressable></View>:stats.map(s=><View key={s.horse.id} style={styles.card}><Pressable onPress={()=>router.push(`/(tabs)/horse/${s.horse.id}`)} style={styles.cardHeader}><View><Text style={styles.horseName}>🐎 {s.horse.name}</Text><Text style={styles.small}>Horse competition record</Text></View><Text style={styles.arrow}>›</Text></Pressable><View style={styles.grid}><StatCell value={String(s.starts)} label="Starts"/><StatCell value={String(s.completed)} label="Completed"/><StatCell value={s.bestRank==null?'—':`#${s.bestRank}`} label="Best rank"/><StatCell value={s.avgRank==null?'—':s.avgRank.toFixed(1)} label="Avg rank"/><StatCell value={String(s.totalFaults)} label="Total faults"/><StatCell value={s.avgScore==null?'—':s.avgScore.toFixed(2)} label="Avg score"/></View>{s.results.length?<View style={styles.results}><Text style={styles.resultsTitle}>Recent results</Text>{s.results.map(r=><Pressable key={r.id} onPress={()=>router.push(`/(tabs)/competition/${r.id}`)} style={styles.resultRow}><View style={styles.resultCopy}><Text style={styles.resultName}>{r.name}</Text><Text style={styles.resultMeta}>{new Date(r.competition_date).toLocaleDateString()}{r.class_name?` · ${r.class_name}`:''}</Text></View><Text style={styles.resultValue}>{r.result_rank!=null?`#${r.result_rank}`:'—'}</Text></Pressable>)}</View>:null}</View>)}
 </ScrollView></SafeAreaView>
}
function StatCell({value,label}:{value:string;label:string}){return <View style={styles.cell}><Text style={styles.cellValue}>{value}</Text><Text style={styles.cellLabel}>{label}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F5F0'},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F5F0'},back:{color:'#0E5A45',fontWeight:'800',marginBottom:14},brand:{fontSize:30,fontWeight:'900',letterSpacing:2.5,color:'#0E5A45'},title:{marginTop:14,fontSize:30,fontWeight:'900'},subtitle:{marginTop:6,fontSize:15,lineHeight:22,opacity:.58},overview:{marginTop:18,padding:16,borderRadius:20,backgroundColor:'#0E5A45',flexDirection:'row',justifyContent:'space-between'},overValue:{fontSize:22,fontWeight:'900',color:'#FFF'},overLabel:{marginTop:3,fontSize:10,fontWeight:'800',color:'#DCEBE5'},card:{marginTop:16,padding:17,borderRadius:20,backgroundColor:'#FFF'},cardHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},horseName:{fontSize:18,fontWeight:'900',color:'#0E5A45'},small:{marginTop:3,fontSize:12,opacity:.5},arrow:{fontSize:24,color:'#0E5A45'},grid:{marginTop:14,flexDirection:'row',flexWrap:'wrap',gap:8},cell:{width:'31%',padding:10,borderRadius:13,backgroundColor:'#F7F5F0'},cellValue:{fontSize:19,fontWeight:'900',color:'#0E5A45'},cellLabel:{marginTop:3,fontSize:10,fontWeight:'700',opacity:.55},results:{marginTop:15},resultsTitle:{fontSize:13,fontWeight:'900'},resultRow:{marginTop:8,paddingVertical:9,borderTopWidth:1,borderTopColor:'#F0EEE8',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},resultCopy:{flex:1},resultName:{fontSize:13,fontWeight:'800'},resultMeta:{marginTop:3,fontSize:11,opacity:.5},resultValue:{fontSize:16,fontWeight:'900',color:'#0E5A45'},empty:{marginTop:22,padding:28,borderRadius:20,backgroundColor:'#FFF',alignItems:'center'},icon:{fontSize:42},emptyTitle:{marginTop:10,fontSize:19,fontWeight:'900'},emptyBody:{marginTop:6,textAlign:'center',lineHeight:20,opacity:.58},primary:{marginTop:16,paddingHorizontal:18,paddingVertical:12,borderRadius:14,backgroundColor:'#0E5A45'},primaryText:{color:'#FFF',fontWeight:'900'},error:{marginTop:14,padding:12,borderRadius:13,backgroundColor:'#FCECEC'},errorText:{color:'#8C2F2F',fontSize:13},muted:{marginTop:6,opacity:.55}});