import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { syncReminderNotifications } from '../../lib/notifications';

type Reminder = { id: string; title: string; description: string | null; reminder_type: string; due_at: string; recurrence_rule: string | null; remind_before_minutes: number; status: string; enabled: boolean; horse_id: string | null };
type Horse = { id: string; name: string };

export default function RemindersTab() {
  const [items,setItems]=useState<Reminder[]>([]); const [horses,setHorses]=useState<Horse[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [syncing,setSyncing]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async(pull=false)=>{if(pull)setRefreshing(true);else setLoading(true);setError(null);const {data:userData}=await supabase.auth.getUser();const user=userData.user;if(!user){setError('Please sign in to view reminders.');setLoading(false);setRefreshing(false);return;}const [{data,error:queryError},{data:horseRows}]=await Promise.all([supabase.from('reminders').select('id,title,description,reminder_type,due_at,recurrence_rule,remind_before_minutes,status,enabled,horse_id').eq('user_id',user.id).eq('status','pending').eq('enabled',true).order('due_at',{ascending:true}),supabase.from('horse_listings').select('id,name').eq('user_id',user.id).order('name')]);if(queryError){setError(queryError.message);setItems([])}else{const reminders=(data??[]) as Reminder[];setItems(reminders);setHorses((horseRows??[]) as Horse[]);setSyncing(true);try{await syncReminderNotifications(reminders)}catch(e){setError(e instanceof Error?e.message:'Could not schedule notifications.')}finally{setSyncing(false)}}setLoading(false);setRefreshing(false)},[]);
  useEffect(()=>{void load()},[load]);
  if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Loading reminders…</Text></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>}>
    <Text style={styles.eyebrow}>SHABDIZ</Text><View style={styles.headingRow}><View><Text style={styles.title}>Reminders</Text><Text style={styles.subtitle}>Your stable tasks — with native notifications.</Text></View><Pressable style={styles.add} onPress={()=>router.push('/(tabs)/add-reminder')}><Text style={styles.addText}>＋ Add</Text></Pressable></View>
    {syncing?<View style={styles.sync}><Text style={styles.syncText}>🔔 Syncing notifications…</Text></View>:null}{error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}
    {items.length===0?<View style={styles.empty}><Text style={styles.emptyIcon}>✅</Text><Text style={styles.emptyTitle}>Nothing due</Text><Text style={styles.muted}>Tap ＋ Add to create your first reminder.</Text></View>:<View style={styles.list}>{items.map(item=><ReminderCard key={item.id} reminder={item} horseName={horses.find(h=>h.id===item.horse_id)?.name}/>)}</View>}
  </ScrollView></SafeAreaView>;
}
function ReminderCard({reminder,horseName}:{reminder:Reminder;horseName?:string}){const due=new Date(reminder.due_at);return <View style={styles.card}><View style={styles.cardTop}><Text style={styles.type}>{reminder.reminder_type.replaceAll('_',' ')}</Text><Text style={styles.when}>{due.toLocaleDateString(undefined,{day:'2-digit',month:'short'})} · {due.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</Text></View><Text style={styles.cardTitle}>{reminder.title}</Text>{horseName?<Text style={styles.horse}>🐎 {horseName}</Text>:<Text style={styles.general}>General stable reminder</Text>}{reminder.description?<Text style={styles.cardBody} numberOfLines={2}>{reminder.description}</Text>:null}<Text style={styles.lead}>🔔 Notify {reminder.remind_before_minutes===0?'at time':`${reminder.remind_before_minutes} min before`}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F5F0'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F5F0'},container:{padding:20,paddingBottom:40},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:2,opacity:.55},headingRow:{marginTop:8,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:12},title:{fontSize:32,fontWeight:'800'},subtitle:{marginTop:6,fontSize:14,lineHeight:20,opacity:.6},add:{paddingHorizontal:15,paddingVertical:11,borderRadius:14,backgroundColor:'#0E5A45'},addText:{color:'#FFF',fontWeight:'900'},sync:{marginTop:16,padding:11,borderRadius:12,backgroundColor:'#E9F3EE'},syncText:{fontSize:13,fontWeight:'700'},list:{marginTop:22,gap:12},card:{padding:17,borderRadius:19,backgroundColor:'#FFF'},cardTop:{flexDirection:'row',justifyContent:'space-between',gap:12},type:{fontSize:11,fontWeight:'800',textTransform:'uppercase',opacity:.5},when:{fontSize:12,fontWeight:'700',opacity:.65},cardTitle:{marginTop:10,fontSize:18,fontWeight:'800'},horse:{marginTop:7,fontSize:13,fontWeight:'800',color:'#0E5A45'},general:{marginTop:7,fontSize:12,fontWeight:'700',opacity:.45},cardBody:{marginTop:7,fontSize:14,lineHeight:20,opacity:.62},lead:{marginTop:13,fontSize:12,fontWeight:'700',color:'#0E5A45'},empty:{marginTop:28,padding:30,borderRadius:22,backgroundColor:'#FFF',alignItems:'center'},emptyIcon:{fontSize:34},emptyTitle:{marginTop:12,fontSize:20,fontWeight:'800'},muted:{marginTop:7,fontSize:14,opacity:.6},error:{marginTop:18,padding:14,borderRadius:14,backgroundColor:'#FCECEC'},errorText:{fontSize:13,lineHeight:18}});
