import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { supabase } from '../../../../lib/supabase';
import { replaceReminderNotification, cancelReminderNotification } from '../../../../lib/notifications';

type Reminder={id:string;title:string;description:string|null;reminder_type:string;due_at:string;remind_before_minutes:number;status:string;enabled:boolean;horse_id:string|null};type Horse={id:string;name:string};
const TYPES=['Vaccination','Farrier','Veterinary','Training','Competition','Other'];const LEADS=[0,60,1440,2880,10080];
export default function ReminderDetailScreen(){
 const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const[reminder,setReminder]=useState<Reminder|null>(null);const[horses,setHorses]=useState<Horse[]>([]);const[title,setTitle]=useState('');const[type,setType]=useState('Veterinary');const[date,setDate]=useState('');const[time,setTime]=useState('');const[lead,setLead]=useState(1440);const[description,setDescription]=useState('');const[horseId,setHorseId]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);const reminderId=Array.isArray(id)?id[0]:id;const{data:{user}}=await supabase.auth.getUser();if(!user||!reminderId){setError('Reminder not found.');setLoading(false);return}const[{data,error:e},{data:hs}]=await Promise.all([supabase.from('reminders').select('id,title,description,reminder_type,due_at,remind_before_minutes,status,enabled,horse_id').eq('id',reminderId).eq('user_id',user.id).maybeSingle(),supabase.from('horse_listings').select('id,name').eq('user_id',user.id).order('name')]);if(e||!data){setError(e?.message??'Reminder not found.');setLoading(false);return}const r=data as Reminder;setReminder(r);setHorses((hs??[]) as Horse[]);setTitle(r.title);setDescription(r.description??'');setType(TYPES.find(x=>x.toLowerCase().replaceAll(' ','_')===r.reminder_type)||'Other');const d=new Date(r.due_at);setDate(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`);setTime(`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`);setLead(r.remind_before_minutes);setHorseId(r.horse_id??'');setLoading(false)},[id]);
 useEffect(()=>{void load()},[load]);
 async function update(){setError(null);if(!title.trim()){setError('Please enter a title.');return}const due=new Date(`${date}T${time}:00`);if(Number.isNaN(due.getTime())||due.getTime()<=Date.now()){setError('Please choose a valid future date and time.');return}setSaving(true);const{data:{user}}=await supabase.auth.getUser();const reminderId=Array.isArray(id)?id[0]:id;if(!user||!reminderId){setError('Please sign in first.');setSaving(false);return}const{data,error:e}=await supabase.from('reminders').update({title:title.trim(),description:description.trim()||null,reminder_type:type.toLowerCase().replaceAll(' ','_'),due_at:due.toISOString(),remind_before_minutes:lead,horse_id:horseId||null,enabled:true,status:'pending'}).eq('id',reminderId).eq('user_id',user.id).select('id,title,description,reminder_type,due_at,remind_before_minutes,horse_id').single();if(e){setError(e.message);setSaving(false);return}try{await replaceReminderNotification(data)}catch(notificationError){console.warn('Unable to reschedule reminder notification',notificationError)}setSaving(false);router.back()}
 async function complete(){const{data:{user}}=await supabase.auth.getUser();const reminderId=Array.isArray(id)?id[0]:id;if(!user||!reminderId)return;const{error:e}=await supabase.from('reminders').update({status:'completed',enabled:false}).eq('id',reminderId).eq('user_id',user.id);if(e){setError(e.message);return}try{await cancelReminderNotification(reminderId)}catch(notificationError){console.warn('Unable to cancel reminder notification',notificationError)}router.back()}
 function confirmComplete(){Alert.alert('Complete reminder?','This will move it out of your active care list.',[{text:'Cancel',style:'cancel'},{text:'Complete',onPress:()=>void complete()}])}
 async function remove(){const{data:{user}}=await supabase.auth.getUser();const reminderId=Array.isArray(id)?id[0]:id;if(!user||!reminderId)return;const{error:e}=await supabase.from('reminders').delete().eq('id',reminderId).eq('user_id',user.id);if(e){setError(e.message);return}try{await cancelReminderNotification(reminderId)}catch(notificationError){console.warn('Unable to cancel reminder notification',notificationError)}router.back()}
 function confirmDelete(){Alert.alert('Delete reminder?','This cannot be undone.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void remove()}])}
 if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Loading reminder…</Text></View>;
 if(!reminder)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.title}>Unable to open reminder</Text><Text style={styles.error}>{error}</Text></View></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Reminders</Text></Pressable><Text style={styles.brand}>SHABDIZ</Text><Text style={styles.title}>Edit Reminder</Text><Text style={styles.subtitle}>Keep every horse-care task current.</Text><View style={styles.card}><Text style={styles.label}>Title</Text><TextInput value={title} onChangeText={setTitle} style={styles.input}/><Text style={styles.label}>Horse</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><Pressable onPress={()=>setHorseId('')} style={[styles.chip,!horseId&&styles.active]}><Text style={[styles.chipText,!horseId&&styles.activeText]}>General</Text></Pressable>{horses.map(h=><Pressable key={h.id} onPress={()=>setHorseId(h.id)} style={[styles.chip,horseId===h.id&&styles.active]}><Text style={[styles.chipText,horseId===h.id&&styles.activeText]}>{h.name}</Text></Pressable>)}</ScrollView><Text style={styles.label}>Type</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{TYPES.map(x=><Pressable key={x} onPress={()=>setType(x)} style={[styles.chip,type===x&&styles.active]}><Text style={[styles.chipText,type===x&&styles.activeText]}>{x}</Text></Pressable>)}</ScrollView><View style={styles.row}><View style={styles.half}><Text style={styles.label}>Date</Text><TextInput value={date} onChangeText={setDate} style={styles.input} placeholder="YYYY-MM-DD"/></View><View style={styles.half}><Text style={styles.label}>Time</Text><TextInput value={time} onChangeText={setTime} style={styles.input} placeholder="HH:MM"/></View></View><Text style={styles.label}>Notify me</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{LEADS.map(m=>{const text=m===0?'At time':m<1440?`${m/60}h before`:`${m/1440}d before`;return <Pressable key={m} onPress={()=>setLead(m)} style={[styles.chip,lead===m&&styles.active]}><Text style={[styles.chipText,lead===m&&styles.activeText]}>{text}</Text></Pressable>})}</ScrollView><Text style={styles.label}>Notes</Text><TextInput value={description} onChangeText={setDescription} style={[styles.input,styles.notes]} multiline/><Text style={styles.meta}>Status: {reminder.status} · {reminder.enabled?'Active':'Disabled'}</Text>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={saving} onPress={()=>void update()} style={styles.primary}><Text style={styles.primaryText}>{saving?'Saving…':'Save changes'}</Text></Pressable><Pressable onPress={confirmComplete} style={styles.complete}><Text style={styles.completeText}>✓ Mark as completed</Text></Pressable><Pressable onPress={confirmDelete} style={styles.delete}><Text style={styles.deleteText}>Delete reminder</Text></Pressable></View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F5F0'},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F5F0',padding:24},back:{color:'#0E5A45',fontWeight:'800',marginBottom:14},brand:{fontSize:30,fontWeight:'900',letterSpacing:2.5,color:'#0E5A45'},title:{marginTop:16,fontSize:30,fontWeight:'900'},subtitle:{marginTop:5,marginBottom:20,fontSize:15,lineHeight:22,color:'#777D79'},card:{backgroundColor:'#FFF',borderRadius:22,padding:18,borderWidth:1,borderColor:'#E1DFD9'},label:{marginTop:10,marginBottom:6,fontSize:12,fontWeight:'800',color:'#777D79'},input:{minHeight:46,borderWidth:1,borderColor:'#DCD9D1',borderRadius:13,paddingHorizontal:12,backgroundColor:'#FAFAF8',fontSize:15},row:{flexDirection:'row',gap:10},half:{flex:1},chips:{gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:16,backgroundColor:'#F1EFE9'},active:{backgroundColor:'#0E5A45'},chipText:{fontWeight:'800',color:'#555C58'},activeText:{color:'#FFF'},notes:{minHeight:90,paddingTop:12,textAlignVertical:'top'},meta:{marginTop:14,fontSize:12,color:'#777D79'},primary:{marginTop:16,minHeight:50,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#0E5A45'},primaryText:{color:'#FFF',fontWeight:'900',fontSize:15},complete:{marginTop:10,minHeight:48,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#E9F3EE'},completeText:{color:'#0E5A45',fontWeight:'900'},delete:{marginTop:10,minHeight:46,alignItems:'center',justifyContent:'center'},deleteText:{color:'#A33A2B',fontWeight:'800'},error:{marginTop:12,color:'#A33A2B',lineHeight:20},muted:{marginTop:8,opacity:.55}});