import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '../../lib/supabase';
import { scheduleReminderNotifications } from '../../lib/notifications';

const C={green:'#174D3F',greenDark:'#103D32',gold:'#D9A93A',cream:'#F7F5F0',white:'#FFFFFF',muted:'#7B817D',line:'#E4E0D7',soft:'#EAF2EE',red:'#A33A2B'};
const TYPES=[['training','Training'],['vaccination','Vaccination'],['dental','Dental'],['farrier','Farrier'],['medication','Medication'],['vet','Vet'],['custom','Custom']] as const;
const LEADS=[[0,'At the time'],[5,'5 minutes'],[10,'10 minutes'],[30,'30 minutes'],[60,'1 hour'],[1440,'1 day'],[2880,'2 days'],[10080,'7 days'],[43200,'30 days']] as const;
const REPEATS=[['','Does not repeat'],['FREQ=DAILY','Every day'],['FREQ=WEEKLY','Every week'],['FREQ=WEEKLY;INTERVAL=2','Every 2 weeks'],['FREQ=WEEKLY;INTERVAL=4','Every 4 weeks'],['FREQ=WEEKLY;INTERVAL=6','Every 6 weeks'],['FREQ=MONTHLY','Every month'],['FREQ=MONTHLY;INTERVAL=6','Every 6 months'],['FREQ=YEARLY','Every year']] as const;
type Horse={id:string;name:string};
type Reminder={id:string;title:string;description:string|null;reminder_type:string;due_at:string;horse_id:string|null;recurrence_rule:string|null;remind_before_minutes:number;status:string;enabled:boolean};
function localParts(iso:string){const d=new Date(iso);return {date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,time:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};}
export default function EditReminderScreen(){
 const{id}=useLocalSearchParams<{id:string}>();const[loading,setLoading]=useState(true);const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[type,setType]=useState('training');const[horseId,setHorseId]=useState('');const[horses,setHorses]=useState<Horse[]>([]);const[date,setDate]=useState('');const[time,setTime]=useState('09:00');const[lead,setLead]=useState(10);const[repeat,setRepeat]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{let mounted=true;(async()=>{if(!id)return;const{data,error:e}=await supabase.from('reminders').select('id,title,description,reminder_type,due_at,horse_id,recurrence_rule,remind_before_minutes,status,enabled').eq('id',id).single();const{data:{user}}=await supabase.auth.getUser();let hs:Horse[]=[];if(user){const[{data:personal},{data:listings}]=await Promise.all([supabase.from('personal_horses').select('id,name').eq('owner_id',user.id).order('name'),supabase.from('horse_listings').select('id,name').eq('user_id',user.id).order('name')]);const map=new Map<string,Horse>();for(const h of personal??[])map.set(h.id,h as Horse);for(const h of listings??[])if(!map.has(h.id))map.set(h.id,h as Horse);hs=Array.from(map.values()).sort((a,b)=>a.name.localeCompare(b.name));}if(mounted){if(e||!data)setError(e?.message||'Reminder not found.');else{const r=data as Reminder;const p=localParts(r.due_at);setTitle(r.title);setDescription(r.description||'');setType(r.reminder_type);setHorseId(r.horse_id||'');setDate(p.date);setTime(p.time);setLead(r.remind_before_minutes);setRepeat(r.recurrence_rule||'');}setHorses(hs);setLoading(false);}})();return()=>{mounted=false;};},[id]);
 const isoDue=useMemo(()=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(date.trim());const t=/^(\d{2}):(\d{2})$/.exec(time.trim());if(!m||!t)return null;const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]),Number(t[1]),Number(t[2]),0,0);return Number.isNaN(d.getTime())?null:d.toISOString();},[date,time]);
 async function save(){setError('');if(!id)return;if(!title.trim()||title.trim().length>120)return setError('Please enter a title (max 120 characters).');if(!isoDue)return setError('Use a valid date (YYYY-MM-DD) and time (HH:MM).');if(Date.parse(isoDue)<=Date.now())return setError('The reminder date must be in the future.');setBusy(true);const payload={horse_id:horseId||null,title:title.trim(),description:description.trim()||null,reminder_type:type,due_at:isoDue,recurrence_rule:repeat||null,remind_before_minutes:lead,status:'pending',enabled:true};const{data:updated,error:e}=await supabase.from('reminders').update(payload).eq('id',id).select('id,title,description,due_at,recurrence_rule,remind_before_minutes,status,enabled').single();if(e||!updated){setBusy(false);return setError(e?.message||'Could not update reminder.');}try{await scheduleReminderNotifications(updated);}catch(err){console.warn('Notification reschedule failed',err);}setBusy(false);router.replace({pathname:'/reminder/[id]',params:{id}});}
 if(loading)return <View style={styles.center}><ActivityIndicator size="large" color={C.green}/><Text style={styles.muted}>Loading reminder…</Text></View>;
 return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.arrow}>‹</Text><Text style={styles.backText}>Back</Text></Pressable><Text style={styles.kicker}>EQUIMASTER PRO</Text><Text style={styles.title}>Edit reminder</Text><Text style={styles.subtitle}>Change the schedule or details, then save.</Text><View style={styles.panel}><Label text="TITLE"/><TextInput value={title} onChangeText={setTitle} maxLength={120} style={styles.input}/><Label text="TYPE"/><View style={styles.chips}>{TYPES.map(([v,l])=><Chip key={v} label={l} active={type===v} onPress={()=>setType(v)}/>)}</View><Label text="HORSE"/><View style={styles.chips}><Chip label="General reminder" active={!horseId} onPress={()=>setHorseId('')}/>{horses.map(h=><Chip key={h.id} label={h.name} active={horseId===h.id} onPress={()=>setHorseId(h.id)}/>)}</View><Label text="DATE"/><TextInput value={date} onChangeText={setDate} keyboardType="numbers-and-punctuation" style={styles.input}/><Label text="TIME"/><TextInput value={time} onChangeText={setTime} keyboardType="numbers-and-punctuation" style={styles.input}/><Label text="REMIND ME BEFORE"/><View style={styles.chips}>{LEADS.map(([v,l])=><Chip key={v} label={l} active={lead===v} onPress={()=>setLead(v)}/>)}</View><Label text="REPEAT"/><View style={styles.chips}>{REPEATS.map(([v,l])=><Chip key={v} label={l} active={repeat===v} onPress={()=>setRepeat(v)}/>)}</View><Label text="NOTES (OPTIONAL)"/><TextInput value={description} onChangeText={setDescription} multiline numberOfLines={4} style={[styles.input,styles.notes]}/>{error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}<Pressable disabled={busy} onPress={()=>void save()} style={({pressed})=>[styles.save,pressed&&styles.pressed,busy&&styles.disabled]}>{busy?<ActivityIndicator color={C.greenDark}/>:<Text style={styles.saveText}>Save changes</Text>}</Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function Label({text}:{text:string}){return <Text style={styles.label}>{text}</Text>;}function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[styles.chip,active&&styles.chipActive,pressed&&styles.pressed]}><Text style={[styles.chipText,active&&styles.chipTextActive]}>{label}</Text></Pressable>;}const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.cream},flex:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:C.cream},container:{padding:20,paddingBottom:44},back:{flexDirection:'row',alignItems:'center',alignSelf:'flex-start',paddingVertical:6},arrow:{color:C.green,fontSize:32,lineHeight:30},backText:{marginLeft:5,color:C.green,fontSize:15,fontWeight:'800'},kicker:{marginTop:20,color:C.gold,fontSize:12,fontWeight:'900',letterSpacing:2.2},title:{marginTop:7,color:C.green,fontSize:36,lineHeight:42,fontWeight:'900'},subtitle:{marginTop:8,color:C.muted,fontSize:15,lineHeight:22},panel:{marginTop:22,padding:20,borderRadius:24,backgroundColor:C.white,borderWidth:1,borderColor:C.line},label:{marginTop:18,marginBottom:8,color:C.green,fontSize:11,letterSpacing:1.5,fontWeight:'900'},input:{minHeight:56,paddingHorizontal:15,borderRadius:15,borderWidth:1,borderColor:C.line,backgroundColor:'#FAFAF8',color:C.green,fontSize:15},notes:{paddingTop:14,minHeight:100,textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:13,paddingVertical:10,borderRadius:13,borderWidth:1,borderColor:C.line,backgroundColor:'#FAFAF8'},chipActive:{borderColor:C.green,backgroundColor:C.soft},chipText:{color:C.muted,fontSize:12,fontWeight:'700'},chipTextActive:{color:C.green},error:{marginTop:16,padding:13,borderRadius:13,backgroundColor:'#F6E9E6'},errorText:{color:C.red,fontSize:13,lineHeight:19,fontWeight:'600'},save:{marginTop:18,minHeight:58,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:C.gold},saveText:{color:C.greenDark,fontSize:16,fontWeight:'900'},muted:{marginTop:8,color:C.muted},pressed:{opacity:.82},disabled:{opacity:.45}});