/**
 * Global horse breed catalog for EquiMaster Pro.
 * Regenerate data.ts with: node scripts/generate-breeds.mjs
 */

function warmblood(name, origin) {
  return { name, category: "warmblood", origin_country: origin, sport_type: "sport" };
}
function registry(name, origin) {
  return { name, category: "sport_horse_registry", origin_country: origin, sport_type: "sport" };
}
function thoroughbred(name, origin) {
  return { name, category: "thoroughbred", origin_country: origin, sport_type: "racing" };
}
function arabian(name, origin) {
  return { name, category: "arabian", origin_country: origin, sport_type: "riding" };
}
function draft(name, origin) {
  return { name, category: "draft", origin_country: origin, sport_type: "draft" };
}
function gaited(name, origin) {
  return { name, category: "gaited", origin_country: origin, sport_type: "gaited" };
}
function iberian(name, origin) {
  return { name, category: "iberian", origin_country: origin, sport_type: "riding" };
}
function baroque(name, origin) {
  return { name, category: "baroque", origin_country: origin, sport_type: "riding" };
}
function coldblood(name, origin) {
  return { name, category: "coldblood", origin_country: origin, sport_type: "draft" };
}
function rare(name, origin, sport_type = "general") {
  return { name, category: "rare_regional", origin_country: origin, sport_type };
}
function miniature(name, origin) {
  return { name, category: "miniature", origin_country: origin, sport_type: "pony" };
}
function crossbreed(name, origin) {
  return { name, category: "crossbreed", origin_country: origin, sport_type: "general" };
}
function other(name, origin) {
  return { name, category: "other", origin_country: origin, sport_type: "general" };
}
function riding(name, origin, category = "rare_regional") {
  return { name, category, origin_country: origin, sport_type: "riding" };
}

export const BREED_CATALOG = [
  // ── German & Central European warmbloods ──
  warmblood("Hanoverian", "Germany"),
  warmblood("Holsteiner", "Germany"),
  warmblood("Oldenburg", "Germany"),
  warmblood("Westphalian", "Germany"),
  warmblood("Rhineland Warmblood", "Germany"),
  warmblood("Bavarian Warmblood", "Germany"),
  warmblood("Baden-Wurttemberg Warmblood", "Germany"),
  warmblood("Zweibrucker", "Germany"),
  warmblood("Trakehner", "Germany"),
  warmblood("Mecklenburger", "Germany"),
  warmblood("Brandenburg Warmblood", "Germany"),
  warmblood("Saxony-Thuringia Warmblood", "Germany"),
  warmblood("Hessian Warmblood", "Germany"),
  warmblood("Schleswig Holstein Warmblood", "Germany"),
  warmblood("Wurttemberger", "Germany"),
  warmblood("East Friesian Warmblood", "Germany"),
  warmblood("Alt-Oldenburg", "Germany"),
  warmblood("Beberbeck Warmblood", "Germany"),
  warmblood("Senner", "Germany"),
  warmblood("ZfdP Sport Horse", "Germany"),

  // ── Dutch & Belgian warmbloods ──
  warmblood("KWPN", "Netherlands, Kingdom of the"),
  warmblood("Gelderlander", "Netherlands, Kingdom of the"),
  warmblood("Groningen Horse", "Netherlands, Kingdom of the"),
  warmblood("Dutch Harness Horse", "Netherlands, Kingdom of the"),
  warmblood("BWP", "Belgium"),
  warmblood("Belgian Warmblood", "Belgium"),
  warmblood("Zangersheide", "Belgium"),

  // ── French & Southern European sport horses ──
  warmblood("Selle Francais", "France"),
  warmblood("Anglo-Normand", "France"),
  warmblood("French Trotter", "France"),
  warmblood("French Saddle Pony", "France"),
  warmblood("Italian Warmblood", "Italy"),
  warmblood("Sardinian Anglo-Arab", "Italy"),
  warmblood("Salerno Horse", "Italy"),
  warmblood("Tolfetano", "Italy"),
  warmblood("Bardigiano", "Italy"),
  warmblood("Avelignese", "Italy"),

  // ── British, Irish & Iberian sport types ──
  warmblood("Irish Sport Horse", "Ireland"),
  warmblood("Irish Draught", "Ireland"),
  warmblood("Connemara Sport Horse", "Ireland"),
  warmblood("Spanish Sport Horse", "Spain"),
  warmblood("Portuguese Sport Horse", "Portugal"),
  warmblood("Swedish Warmblood", "Sweden"),
  warmblood("Danish Warmblood", "Denmark"),
  warmblood("Finnish Warmblood", "Finland"),
  warmblood("Norwegian Warmblood", "Norway"),
  warmblood("Swiss Warmblood", "Switzerland"),
  warmblood("Austrian Warmblood", "Austria"),
  warmblood("Hungarian Sport Horse", "Hungary"),
  warmblood("Romanian Sport Horse", "Romania"),
  warmblood("Czech Warmblood", "Czechia"),
  warmblood("Slovak Warmblood", "Slovakia"),
  warmblood("Polish Warmblood", "Poland"),
  warmblood("Wielkopolski", "Poland"),
  warmblood("Malopolski", "Poland"),
  warmblood("Silesian Horse", "Poland"),
  warmblood("East Bulgarian", "Bulgaria"),
  warmblood("Bulgarian Sport Horse", "Bulgaria"),
  warmblood("Ukrainian Riding Horse", "Ukraine"),
  warmblood("Russian Warmblood", "Russian Federation"),
  warmblood("Latvian Warmblood", "Latvia"),
  warmblood("Lithuanian Warmblood", "Lithuania"),
  warmblood("Estonian Native", "Estonia"),
  warmblood("Toric", "Slovenia"),
  warmblood("Nonius", "Hungary"),
  warmblood("Furioso-North Star", "Hungary"),
  warmblood("Gidran", "Hungary"),
  warmblood("Kisber Felver", "Hungary"),
  warmblood("Shagya Sport Horse", "Hungary"),

  // ── Sport horse registries & studbooks ──
  registry("AES", "France"),
  registry("Anglo European Studbook", "United Kingdom"),
  registry("DSP", "Germany"),
  registry("OS", "Germany"),
  registry("Westfalen", "Germany"),
  registry("Rheinland Pfalz Saar International", "Germany"),
  registry("Belgian Sport Horse", "Belgium"),
  registry("Irish Horse Board", "Ireland"),
  registry("Studbook Zangersheide", "Belgium"),
  registry("Warmblood Studbook of Ireland", "Ireland"),
  registry("Canadian Sport Horse", "Canada"),
  registry("Australian Warmblood", "Australia"),
  registry("New Zealand Warmblood", "New Zealand"),
  registry("South African Warmblood", "South Africa"),
  registry("Brazilian Sport Horse", "Brazil"),
  registry("Chilean Sport Horse", "Chile"),
  registry("Mexican Sport Horse", "Mexico"),
  registry("Colombian Sport Horse", "Colombia"),
  registry("Argentinian Sport Horse", "Argentina"),

  // ── Thoroughbred & racing ──
  thoroughbred("Thoroughbred", "United Kingdom"),
  thoroughbred("American Thoroughbred", "United States of America"),
  thoroughbred("Australian Thoroughbred", "Australia"),
  thoroughbred("Japanese Thoroughbred", "Japan"),
  thoroughbred("Irish Thoroughbred", "Ireland"),
  thoroughbred("French Thoroughbred", "France"),
  thoroughbred("Standardbred", "United States of America"),
  thoroughbred("Orlov Trotter", "Russian Federation"),
  thoroughbred("French Trotter Horse", "France"),
  thoroughbred("Finnhorse Trotter", "Finland"),
  thoroughbred("Russian Trotter", "Russian Federation"),
  thoroughbred("Monte Horse", "Italy"),
  thoroughbred("Anglo-Arabian Trotter", "France"),

  // ── Arabian & related ──
  arabian("Arabian", "Saudi Arabia"),
  arabian("Polish Arabian", "Poland"),
  arabian("Russian Arabian", "Russian Federation"),
  arabian("Egyptian Arabian", "Egypt"),
  arabian("Crabbet Arabian", "United Kingdom"),
  arabian("Spanish Arabian", "Spain"),
  arabian("Shagya Arabian", "Hungary"),
  arabian("Anglo Arabian", "France"),
  arabian("Part-Arabian", "United States of America"),
  arabian("Moroccan Arabian", "Morocco"),
  arabian("Syrian Arabian", "Syrian Arab Republic"),
  arabian("Asil Arabian", "Saudi Arabia"),
  arabian("Bedouin Arabian", "Saudi Arabia"),
  arabian("Straight Egyptian", "Egypt"),
  arabian("Desertbred Arabian", "Saudi Arabia"),

  // ── Iberian ──
  iberian("Andalusian (PRE)", "Spain"),
  iberian("Lusitano", "Portugal"),
  iberian("Sorraia", "Portugal"),
  iberian("Alter Real", "Portugal"),
  iberian("Menorquin", "Spain"),
  iberian("Pottoka", "Spain"),
  iberian("Asturcon", "Spain"),
  iberian("Losino", "Spain"),
  iberian("Marismeno", "Spain"),
  iberian("Caballo de Deporte Espanol", "Spain"),
  iberian("Portuguese Sport Pony", "Portugal"),

  // ── Baroque ──
  baroque("Lipizzaner", "Austria"),
  baroque("Frederiksborger", "Denmark"),
  baroque("Kladruber", "Czechia"),
  baroque("Knabstrupper", "Denmark"),
  baroque("Baroque Pinto", "Netherlands, Kingdom of the"),
  baroque("Friesian Baroque", "Netherlands, Kingdom of the"),
  baroque("Baroque Warmblood", "Germany"),
  baroque("Neapolitan Horse", "Italy"),

  // ── Friesian & related ──
  riding("Friesian", "Netherlands, Kingdom of the", "baroque"),
  riding("Frederiksborg", "Denmark", "baroque"),

  // ── Gaited ──
  gaited("Tennessee Walking Horse", "United States of America"),
  gaited("Missouri Fox Trotter", "United States of America"),
  gaited("Icelandic Horse", "Iceland"),
  gaited("Paso Fino", "Colombia"),
  gaited("Peruvian Paso", "Peru"),
  gaited("Racking Horse", "United States of America"),
  gaited("Rocky Mountain Horse", "United States of America"),
  gaited("Kentucky Mountain Saddle Horse", "United States of America"),
  gaited("Spotted Saddle Horse", "United States of America"),
  gaited("Spotted Mountain Horse", "United States of America"),
  gaited("Mangalarga Marchador", "Brazil"),
  gaited("Campolina", "Brazil"),
  gaited("Crioulo Gaited", "Brazil"),
  gaited("Paso Fino Colombiano", "Colombia"),
  gaited("Paso Fino Puerto Riqueno", "Puerto Rico"),
  gaited("Paso Fino Americano", "United States of America"),
  gaited("Gaited Morgan", "United States of America"),
  gaited("Gaited Spanish Mustang", "United States of America"),
  gaited("Walkaloosa", "United States of America"),
  gaited("Single-Footing Horse", "United States of America"),
  gaited("Florida Cracker Horse", "United States of America"),
  gaited("Narragansett Pacer", "United States of America"),
  gaited("Aegidienberger", "Germany"),
  gaited("Marwari Gaited", "India"),
  gaited("Yakutian Horse", "Russian Federation"),
  gaited("Bashkir Curly", "Russian Federation"),
  gaited("Hequ", "China"),
  gaited("Yili Horse", "China"),
  gaited("Choctaw Horse", "United States of America"),
  gaited("Saddlebred", "United States of America"),
  gaited("American Saddlebred", "United States of America"),
  gaited("National Show Horse", "United States of America"),

  // ── American riding breeds ──
  riding("Quarter Horse", "United States of America", "rare_regional"),
  riding("Paint Horse", "United States of America", "rare_regional"),
  riding("Appaloosa", "United States of America", "rare_regional"),
  riding("Morgan", "United States of America", "rare_regional"),
  riding("Mustang", "United States of America", "rare_regional"),
  riding("American Warmblood", "United States of America", "warmblood"),
  riding("Azteca", "Mexico", "rare_regional"),
  riding("Criollo", "Argentina", "rare_regional"),
  riding("Brazilian Crioulo", "Brazil", "rare_regional"),
  riding("Chilean Corralero", "Chile", "rare_regional"),
  riding("Colonial Spanish Horse", "United States of America", "rare_regional"),
  riding("Spanish Mustang", "United States of America", "rare_regional"),
  riding("Banker Horse", "United States of America", "rare_regional"),
  riding("Chincoteague Pony", "United States of America", "pony"),
  riding("Nokota Horse", "United States of America", "rare_regional"),
  riding("American Cream Draft", "United States of America", "draft"),
  riding("American Bashkir Curly", "United States of America", "gaited"),
  riding("Colorado Ranger", "United States of America", "rare_regional"),
  crossbreed("Morab", "United States of America"),
  crossbreed("Quarab", "United States of America"),
  crossbreed("Appendix Quarter Horse", "United States of America"),

  // ── British native & riding ──
  riding("Cleveland Bay", "United Kingdom", "rare_regional"),
  riding("Hackney", "United Kingdom", "rare_regional"),
  riding("Hackney Pony", "United Kingdom", "pony"),
  riding("Dales Pony", "United Kingdom", "pony"),
  riding("Fell Pony", "United Kingdom", "pony"),
  riding("Highland Pony", "United Kingdom", "pony"),
  riding("Eriskay Pony", "United Kingdom", "pony"),
  riding("Kerry Bog Pony", "Ireland", "pony"),
  riding("New Forest Pony", "United Kingdom", "pony"),
  riding("Dartmoor Pony", "United Kingdom", "pony"),
  riding("Exmoor Pony", "United Kingdom", "pony"),
  riding("Shetland Pony", "United Kingdom", "pony"),
  riding("Welsh Pony", "United Kingdom", "pony"),
  riding("Welsh Section A", "United Kingdom", "pony"),
  riding("Welsh Section B", "United Kingdom", "pony"),
  riding("Welsh Section C", "United Kingdom", "pony"),
  riding("Welsh Section D", "United Kingdom", "pony"),
  riding("Connemara Pony", "Ireland", "pony"),
  riding("German Riding Pony", "Germany", "pony"),
  riding("British Riding Pony", "United Kingdom", "pony"),
  riding("Shetland Pony (American)", "United States of America", "pony"),
  riding("Pony of the Americas", "United States of America", "pony"),
  riding("Gotland Pony", "Sweden", "pony"),
  riding("Gotland Russ", "Sweden", "pony"),
  riding("North Swedish Horse", "Sweden", "coldblood"),
  riding("Fjord", "Norway", "pony"),
  riding("Haflinger", "Austria", "pony"),
  riding("Hucul Pony", "Romania", "pony"),
  riding("Konik", "Poland", "pony"),
  riding("Merens Pony", "France", "pony"),
  riding("Pottok", "France", "pony"),
  riding("Sorraia Pony", "Portugal", "pony"),
  riding("Skyros Pony", "Greece", "pony"),
  riding("Bosnian Mountain Horse", "Bosnia and Herzegovina", "pony"),

  // ── Draft horses ──
  draft("Percheron", "France"),
  draft("Clydesdale", "United Kingdom"),
  draft("Shire", "United Kingdom"),
  draft("Suffolk Punch", "United Kingdom"),
  draft("Belgian Draft", "Belgium"),
  draft("Ardennes", "Belgium"),
  draft("Noriker", "Austria"),
  draft("Black Forest Horse", "Germany"),
  draft("Gypsy Vanner", "United Kingdom"),
  draft("Gypsy Cob", "United Kingdom"),
  draft("Irish Cob", "Ireland"),
  draft("Tinker Horse", "United Kingdom"),
  draft("Drum Horse", "United Kingdom"),
  draft("Boulonnais", "France"),
  draft("Comtois", "France"),
  draft("Auxois", "France"),
  draft("Trait du Nord", "France"),
  draft("Poitevin", "France"),
  draft("Mulassier", "France"),
  draft("Freiberger", "Switzerland"),
  draft("Jutland", "Denmark"),
  draft("Schleswig Coldblood", "Germany"),
  draft("Rhenish German Coldblood", "Germany"),
  draft("South German Coldblood", "Germany"),
  draft("Saxon-Thuringian Coldblood", "Germany"),
  draft("Pinzgauer", "Austria"),
  draft("Norwegian Fjord Draft", "Norway"),
  draft("Dole Gudbrandsdal", "Norway"),
  draft("North Swedish Coldblood", "Sweden"),
  draft("Finnhorse", "Finland"),
  draft("Estonian Draft", "Estonia"),
  draft("Torik", "Hungary"),
  draft("Murakoz", "Hungary"),
  draft("Hungarian Draft", "Hungary"),
  draft("Polish Draft", "Poland"),
  draft("Silesian Draft", "Poland"),
  draft("Czech Coldblood", "Czechia"),
  draft("Slovak Coldblood", "Slovakia"),
  draft("Budapest Coldblood", "Hungary"),
  draft("Russian Heavy Draft", "Russian Federation"),
  draft("Soviet Heavy Draft", "Russian Federation"),
  draft("Vladimir Heavy Draft", "Russian Federation"),
  draft("Suffolk Horse", "United Kingdom"),
  draft("American Cream Draft Horse", "United States of America"),
  draft("Belgian Horse", "Belgium"),
  draft("Brabant", "Belgium"),
  draft("Italian Heavy Draft", "Italy"),
  draft("Brenda", "Italy"),
  draft("Maremmano Draft", "Italy"),

  // ── Coldblood (additional) ──
  coldblood("Schwarzwald Coldblood", "Germany"),
  coldblood("Abtenauer", "Austria"),
  coldblood("Altmark Coldblood", "Germany"),
  coldblood("Bosnian Mountain Pony", "Bosnia and Herzegovina"),
  coldblood("Bosnian Pony", "Bosnia and Herzegovina"),
  coldblood("Boulonnais Draft", "France"),
  coldblood("Brabant Coldblood", "Belgium"),
  coldblood("Breton", "France"),
  coldblood("Boulonnais Horse", "France"),
  coldblood("Carpathian Coldblood", "Romania"),
  coldblood("Croatian Coldblood", "Croatia"),
  coldblood("Danish Coldblood", "Denmark"),
  coldblood("Dutch Draft", "Netherlands, Kingdom of the"),
  coldblood("East Bulgarian Heavy", "Bulgaria"),
  coldblood("Flemish Horse", "Belgium"),
  coldblood("Friesian Cross Draft", "Netherlands, Kingdom of the"),
  coldblood("Groningen Coldblood", "Netherlands, Kingdom of the"),
  coldblood("Heck Horse", "Germany"),
  coldblood("Hequ Horse", "China"),
  coldblood("Jutland Horse", "Denmark"),
  coldblood("Latvian Coldblood", "Latvia"),
  coldblood("Lithuanian Coldblood", "Lithuania"),
  coldblood("Mecklenburg Coldblood", "Germany"),
  coldblood("Murgese Draft", "Italy"),
  coldblood("Norwegian Coldblood Trotter", "Norway"),
  coldblood("Polish Coldblood", "Poland"),
  coldblood("Romanian Coldblood", "Romania"),
  coldblood("Russian Coldblood", "Russian Federation"),
  coldblood("Serbian Coldblood", "Serbia"),
  coldblood("Slovak Coldblood Horse", "Slovakia"),
  coldblood("Swedish Ardennes", "Sweden"),
  coldblood("Swedish Coldblood", "Sweden"),
  coldblood("Tarpan", "Poland"),
  coldblood("Ukrainian Coldblood", "Ukraine"),
  coldblood("Zemaitukas", "Lithuania"),
  coldblood("Zemaituka", "Lithuania"),
  coldblood("Zhemaichu", "Lithuania"),

  // ── Miniature ──
  miniature("Miniature Horse", "United States of America"),
  miniature("Falabella", "Argentina"),
  miniature("American Miniature Horse", "United States of America"),
  miniature("Miniature Shetland", "United Kingdom"),
  miniature("Miniature Appaloosa", "United States of America"),
  miniature("Miniature Donkey Cross", "United States of America"),
  miniature("Dutch Miniature Horse", "Netherlands, Kingdom of the"),
  miniature("South African Miniature Horse", "South Africa"),

  // ── Rare & regional (Europe) ──
  rare("Akhal-Teke", "Turkiye", "riding"),
  rare("Karabakh", "Azerbaijan", "riding"),
  rare("Don Horse", "Russian Federation", "riding"),
  rare("Budyonny", "Russian Federation", "riding"),
  rare("Kabarda", "Russian Federation", "riding"),
  rare("Lokai", "Tajikistan", "riding"),
  rare("Kustanai", "Kazakhstan", "riding"),
  rare("Kazakh Horse", "Kazakhstan", "riding"),
  rare("Altai Horse", "Russian Federation", "riding"),
  rare("Yakut", "Russian Federation", "riding"),
  rare("Tersk", "Russian Federation", "riding"),
  rare("Karachai", "Russian Federation", "riding"),
  rare("Lokai Horse", "Tajikistan", "riding"),
  rare("Camargue", "France", "riding"),
  rare("Maremmano", "Italy", "riding"),
  rare("Murgese", "Italy", "riding"),
  rare("Giara Horse", "Italy", "riding"),
  rare("Tolfetana", "Italy", "riding"),
  rare("Bardigiano Pony", "Italy", "pony"),
  rare("Esperia Pony", "Italy", "pony"),
  rare("Monterufoli Pony", "Italy", "pony"),
  rare("Tarpan Horse", "Poland", "riding"),
  rare("Hucul", "Romania", "pony"),
  rare("Bosnian Mountain Horse", "Bosnia and Herzegovina", "riding"),
  rare("Posavac", "Croatia", "riding"),
  rare("Slavonian Coldblood", "Croatia", "draft"),
  rare("Murakozi", "Hungary", "draft"),
  rare("Gooikoers", "Belgium", "riding"),
  rare("Belgian Riding Pony", "Belgium", "pony"),
  rare("Flemish Horse", "Belgium", "draft"),
  rare("Brabant Horse", "Belgium", "draft"),
  rare("Dutch Tuigpaard", "Netherlands, Kingdom of the", "driving"),
  rare("Groningen", "Netherlands, Kingdom of the", "riding"),
  warmblood("Danish Oldenburg", "Denmark"),
  baroque("Frederiksborg Horse", "Denmark"),
  rare("Gotland Horse", "Sweden", "riding"),
  rare("Gotland Pony", "Sweden", "pony"),
  rare("Northlands Horse", "Sweden", "riding"),
  rare("Swedish Ardennes Horse", "Sweden", "draft"),
  rare("Universal Horse", "Sweden", "riding"),
  rare("Lyngshest", "Norway", "riding"),
  rare("Lofoten Horse", "Norway", "riding"),
  rare("Dole", "Norway", "draft"),
  rare("Finnhorse Universal", "Finland", "dual_purpose"),
  rare("Estonian Horse", "Estonia", "riding"),
  rare("Latvian Horse", "Latvia", "riding"),
  rare("Lithuanian Native", "Lithuania", "riding"),
  rare("Zemaitukas Horse", "Lithuania", "riding"),
  rare("Hucul Horse", "Romania", "pony"),
  rare("Romanian Saddle Horse", "Romania", "riding"),
  rare("Bulgarian Native", "Bulgaria", "riding"),
  rare("East Bulgarian Horse", "Bulgaria", "riding"),
  rare("Karachai-Balkar", "Russian Federation", "riding"),
  rare("Kabardin", "Russian Federation", "riding"),
  rare("Caspian Horse", "Iran, Islamic Republic of", "riding"),
  rare("Turkoman", "Turkiye", "riding"),
  rare("Anatolian Horse", "Turkiye", "riding"),
  rare("Karacabey", "Turkiye", "riding"),

  // ── Rare & regional (Asia) ──
  rare("Marwari", "India", "riding"),
  rare("Kathiawari", "India", "riding"),
  rare("Manipuri Pony", "India", "pony"),
  rare("Bhutia Pony", "India", "pony"),
  rare("Spiti Pony", "India", "pony"),
  rare("Zanskari", "India", "pony"),
  rare("Chummarti", "India", "pony"),
  rare("Bhutia Horse", "India", "riding"),
  rare("Indian Country Bred", "India", "general"),
  rare("Chincoteague", "United States of America", "pony"),
  rare("Mongolian Horse", "Mongolia", "riding"),
  rare("Hequ Horse", "China", "riding"),
  rare("Guoxia", "China", "pony"),
  rare("Baise Horse", "China", "riding"),
  rare("Yunnan Horse", "China", "riding"),
  rare("Tibetan Pony", "China", "pony"),
  rare("Nangchen Horse", "China", "riding"),
  rare("Heihe Horse", "China", "riding"),
  rare("Jinzhou Horse", "China", "riding"),
  rare("Lijiang Horse", "China", "riding"),
  rare("Riwoche Horse", "China", "riding"),
  rare("Balikun Horse", "China", "riding"),
  rare("Kazakh Steppe Horse", "Kazakhstan", "riding"),
  rare("Kyrgyz Horse", "Kyrgyzstan", "riding"),
  rare("Uzbek Horse", "Uzbekistan", "riding"),
  rare("Turkmen Ahalteke", "Turkmenistan", "riding"),
  rare("Japanese Horse", "Japan", "riding"),
  rare("Kiso Horse", "Japan", "riding"),
  rare("Miyako Horse", "Japan", "riding"),
  rare("Noma Horse", "Japan", "pony"),
  rare("Taishu Horse", "Japan", "riding"),
  rare("Yonaguni Horse", "Japan", "pony"),
  rare("Jeju Horse", "Korea, Republic of", "riding"),
  rare("Jeju Pony", "Korea, Republic of", "pony"),
  rare("Cheju Horse", "Korea, Republic of", "riding"),
  rare("Philippine Horse", "Philippines", "riding"),
  rare("Timor Pony", "Timor-Leste", "pony"),
  rare("Sumba Pony", "Indonesia", "pony"),
  rare("Sandalwood Pony", "Indonesia", "pony"),
  rare("Bali Pony", "Indonesia", "pony"),
  rare("Java Pony", "Indonesia", "pony"),
  crossbreed("Thoroughbred Cross (Asia)", "Japan"),
  rare("Vietnamese Horse", "Viet Nam", "riding"),
  rare("Cambodian Pony", "Cambodia", "pony"),
  rare("Myanmar Pony", "Myanmar", "pony"),
  rare("Bhutanese Horse", "Bhutan", "riding"),
  rare("Sri Lankan Pony", "Sri Lanka", "pony"),
  rare("Pakistan Horse", "Pakistan", "riding"),
  rare("Baluchi Horse", "Pakistan", "riding"),
  rare("Khorasani", "Iran, Islamic Republic of", "riding"),
  crossbreed("Arabian Cross (Persian)", "Iran, Islamic Republic of"),

  // ── Rare & regional (Africa & Middle East) ──
  rare("Barb", "Morocco", "riding"),
  rare("Berber", "Morocco", "riding"),
  rare("Atlas Mountain Horse", "Morocco", "riding"),
  rare("Somali Pony", "Somalia", "pony"),
  rare("Abyssinian Horse", "Ethiopia", "riding"),
  rare("Ethiopian Horse", "Ethiopia", "riding"),
  rare("Basotho Pony", "Lesotho", "pony"),
  rare("Nooitgedacht Pony", "South Africa", "pony"),
  rare("Boerperd", "South Africa", "riding"),
  rare("Cape Horse", "South Africa", "riding"),
  rare("Namib Desert Horse", "Namibia", "riding"),
  rare("Zimbabwean Horse", "Zimbabwe", "riding"),
  rare("Kenyan Pony", "Kenya", "pony"),
  rare("West African Barb", "Senegal", "riding"),
  rare("Poney Mousseye", "Cameroon", "pony"),
  rare("Poney du Logone", "Chad", "pony"),
  rare("Dongola Horse", "Sudan", "riding"),
  rare("Egyptian Horse", "Egypt", "riding"),
  rare("Syrian Horse", "Syrian Arab Republic", "riding"),
  rare("Jordanian Horse", "Jordan", "riding"),
  rare("Israeli Horse", "Israel", "riding"),
  arabian("Persian Arabian", "Iran, Islamic Republic of"),

  // ── Rare & regional (Americas & Oceania) ──
  rare("Canadian Horse", "Canada", "riding"),
  rare("Newfoundland Pony", "Canada", "pony"),
  rare("Sable Island Horse", "Canada", "riding"),
  rare("Lac La Croix Pony", "Canada", "pony"),
  rare("Quebec Horse", "Canada", "riding"),
  rare("Australian Stock Horse", "Australia", "riding"),
  rare("Brumby", "Australia", "riding"),
  rare("Waler", "Australia", "riding"),
  rare("Australian Pony", "Australia", "pony"),
  rare("Australian Riding Pony", "Australia", "pony"),
  rare("Australian Draught Horse", "Australia", "draft"),
  rare("New Zealand Horse", "New Zealand", "riding"),
  rare("Kaimanawa Horse", "New Zealand", "riding"),
  rare("New Zealand Pony", "New Zealand", "pony"),
  rare("Criollo Argentino", "Argentina", "riding"),
  rare("Criollo Uruguayo", "Uruguay", "riding"),
  rare("Criollo Venezolano", "Venezuela, Bolivarian Republic of", "riding"),
  rare("Pantaneiro", "Brazil", "riding"),
  rare("Mangalarga", "Brazil", "riding"),
  rare("Baixadeiro", "Brazil", "riding"),
  rare("Campeiro", "Brazil", "riding"),
  rare("Curico", "Chile", "riding"),
  rare("Chilean Horse", "Chile", "riding"),
  rare("Colombian Creole", "Colombia", "riding"),
  rare("Ecuadorian Horse", "Ecuador", "riding"),
  rare("Peruvian Horse", "Peru", "gaited"),
  rare("Puerto Rican Paso Fino", "Puerto Rico", "gaited"),
  rare("Cuban Trotter", "Cuba", "gaited"),
  rare("Galiceno", "Mexico", "riding"),
  rare("Mexican Criollo", "Mexico", "riding"),
  rare("Colonial Horse", "United States of America", "riding"),
  iberian("Spanish Barb", "United States of America"),
  rare("Cerbat Mustang", "United States of America", "riding"),
  rare("Kiger Mustang", "United States of America", "riding"),
  rare("Sulphur Springs Mustang", "United States of America", "riding"),
  rare("Pryor Mountain Mustang", "United States of America", "riding"),
  rare("Haitian Creole", "Haiti", "riding"),
  rare("Jamaican Horse", "Jamaica", "riding"),
  rare("Bahamian Horse", "Bahamas", "riding"),

  // ── Crossbreeds ──
  crossbreed("Warmblood Cross", "Germany"),
  crossbreed("Thoroughbred Cross", "United Kingdom"),
  crossbreed("Sport Horse Cross", "France"),
  crossbreed("Anglo-Arab Cross", "France"),
  crossbreed("Draft Cross", "United States of America"),
  crossbreed("Grade Horse", "United States of America"),
  crossbreed("Mixed Breed", "United States of America"),
  crossbreed("Irish Cross", "Ireland"),
  crossbreed("European Cross", "Germany"),
  crossbreed("Pony Cross", "United Kingdom"),
  crossbreed("Warmblood x Thoroughbred", "Germany"),
  crossbreed("Registered Crossbreed", "United States of America"),
  crossbreed("Part-Bred Arabian", "United Kingdom"),

  // ── Other ──
  other("Unknown", "Unknown"),
  other("Other", "Unknown"),
];
