import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { BREED_CATALOG } from "./breeds-catalog.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function toId(name) {
  return name
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

function dedupeCatalog(entries) {
  const seenNames = new Set();
  const seenIds = new Set();
  const result = [];

  for (const entry of entries) {
    const nameKey = entry.name.trim().toLowerCase();
    if (seenNames.has(nameKey)) continue;
    seenNames.add(nameKey);

    let id = toId(entry.name);
    if (seenIds.has(id)) {
      let suffix = 2;
      while (seenIds.has(`${id}_${suffix}`)) suffix += 1;
      id = `${id}_${suffix}`;
    }
    seenIds.add(id);

    result.push({
      id,
      name: entry.name.trim(),
      category: entry.category,
      origin_country: entry.origin_country,
      sport_type: entry.sport_type,
      is_active: true,
      sort_order: 0,
    });
  }

  return result.sort((a, b) => a.name.localeCompare(b.name));
}

const breeds = dedupeCatalog(BREED_CATALOG).map((breed, index) => ({
  ...breed,
  sort_order: index + 1,
}));

const outPath = path.join(__dirname, "..", "app", "lib", "breeds", "data.ts");
const header = `import type { HorseBreed } from "@/app/lib/breeds/types";

/** Global horse breed registry — generated by scripts/generate-breeds.mjs */
export const HORSE_BREEDS: readonly HorseBreed[] = `;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header + JSON.stringify(breeds, null, 2) + " as const;\n");
console.log(`Wrote ${breeds.length} breeds to ${outPath}`);
