import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { supabase } from '../../../../lib/supabase';

type RecordItem={id:string;record_type:string;record_date:string;title:string;provider:string|null;notes:string|null};
type Horse={id:string;name:string};
const TYPES=['Vaccination','Veterinary','Farrier','Dental','Medication','Other'];
export default function HorseHealthScreen(){const {horseId}=useLocalSearchParams<{horseId:string}>();const router=useRouter();const [horse,setHorse]=useState<Horse|null>(null);const [records,setRecords]=useState<RecordItem[]>([]);const [type,setType]=useState('Veterinary');const [title,setTitle]=useState('');const [date,setDate]=useState('');const [provider,setProvider]=useState('');const [notes,setNotes]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);
const load=useCallback(async()=>{setLoading(true);setError(null);const hid=Array.isArray(horseId)?horseId[0]:horseId;const {data:{user}}=await supabase.auth.getUser();if(!user||!hid){setError('Horse not found.');setLoading(false);return;}const [{data:h,error:he},{data:r,error:re}]=await Promise.all([supabase.from('horse_listings').select('id,name').eq('id',hid).eq('user_id',user.id).maybeSingle(),supabase.from('horse_health_records').select('id,record_type,record_date,title,provider,notes').eq('horse_id',hid).eq('user_id',user.id).order('record_date',{ascending:false}).limit(50)]);if(he||!h)setError(he?.message??'Horse not found.');else setHorse(h as Horse);if(re)setError(re.message);else setRecords((r??[]) as RecordItem[]);const now=new Date();setDate(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`);setLoading(false)},[horseId]);
useEffect(()=>{void load()},[load]);
async function add(){setError(null);if(!title.trim()){setError('Please enter a record title.');return;}const d=new Date(`${date}T12:00:00`);if(Number.isNaN(d.getTime())){setError('Use date YYYY-MM-DD.');return;}setSaving(true);const {data:{user}}=await supabase.auth.getUser();const hid=Array.isArray(horseId)?horseId[0]:horseId;if(!user||!hid){setError('Please sign in first.');setSaving(false);return;}const {error:e}=await supabase.from('horse_health_records').insert({user_id:user.id,horse_id:hid,record_type:type.toLowerCase(),record_date:d.toISOString(),title:title.trim(),provider:provider.trim()||null,notes:notes.trim()||null});if(e)setError(e.message);else{setTitle('');setProvider('');setNotes('');await load()}setSaving(false)}
if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Loading health record…</Text></View>;
if(!horse)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.title}>Unable to open health record</Text><Text style={styles.error}>{error}</Text></View></SafeAreaView>;
return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ {horse.name}</Text></Pressable><Text style={styles.brand}>SHABDIZ</Text><Text style={styles.title}>Health Record</Text><Text style={styles.subtitle}>A permanent care timeline for {horse.name}.</Text><View style={styles.card}><Text style={styles.section}>＋ Add care record</Text><Text style={styles.label}>Type</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{TYPES.map(x=><Pressable key={x} onPress={()=>setType(x)} style={[styles.chip,type===x&&styles.active]}><Text style={[styles.chipText,type===x&&styles.activeText]}>{x}</Text></Pressable>)}</ScrollView><Text style={styles.label}>Title</Text><TextInput value={title} onChangeText={setTitle} style={styles.input} placeholder="e.g. Annual vaccination"/><Text style={styles.label}>Date</Text><TextInput value={date} onChangeText={setDate} style={styles.input} placeholder="YYYY-MM-DD"/><Text style={styles.label}>Provider</Text><TextInput value={provider} onChangeText={setProvider} style={styles.input} placeholder="Vet / farrier / clinic"/><Text style={styles.label}>Notes</Text><TextInput value={notes} onChangeText={setNotes} style={[styles.input,styles.notes]} multiline placeholder="Treatment, findings, medication…"/>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={saving} onPress={()=>void add()} style={styles.primary}><Text style={styles.primaryText}>{saving?'Saving…':'Save record'}</Text></Pressable></View><Text style={styles.timelineTitle}>Care timeline</Text>{records.length===0?<View style={styles.empty}><Text style={styles.emptyIcon}>🩺</Text><Text style={styles.emptyTitle}>No health records yet</Text><Text style={styles.muted}>Add the first vaccination, vet, farrier or dental record above.</Text></View>:records.map(r=><View key={r.id} style={styles.record}><View style={styles.dot}/><View style={styles.recordCopy}><View style={styles.recordTop}><Text style={styles.recordType}>{r.record_type.replaceAll('_',' ')}</Text><Text style={styles.recordDate}>{new Date(r.record_date).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'})}</Text></View><Text style={styles.recordTitle}>{r.title}</Text>{r.provider?<Text style={styles.provider}>👤 {r.provider}</Text>:null}{r.notes?<Text style={styles.notesText}>{r.notes}</Text>:null}</View></View>)}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F5F0'},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F5F0',padding:24},back:{color:'#0E5A45',fontWeight:'800',marginBottom:14},brand:{fontSize:30,fontWeight:'900',letterSpacing:2.5,color:'#0E5A45'},title:{marginTop:16,fontSize:30,fontWeight:'900'},subtitle:{marginTop:5,marginBottom:20,fontSize:15,lineHeight:22,color:'#777D79'},card:{backgroundColor:'#FFF',borderRadius:22,padding:18,borderWidth:1,borderColor:'#E1DFD9'},section:{fontSize:19,fontWeight:'900',marginBottom:8},label:{marginTop:10,marginBottom:6,fontSize:12,fontWeight:'800',color:'#777D79'},chips:{gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:16,backgroundColor:'#F1EFE9'},active:{backgroundColor:'#0E5A45'},chipText:{fontWeight:'800',color:'#555C58'},activeText:{color:'#FFF'},input:{minHeight:46,borderWidth:1,borderColor:'#DCD9D1',borderRadius:13,paddingHorizontal:12,backgroundColor:'#FAFAF8',fontSize:15},notes:{minHeight:90,paddingTop:12,textAlignVertical:'top'},primary:{marginTop:16,minHeight:50,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#0E5A45'},primaryText:{color:'#FFF',fontWeight:'900'},timelineTitle:{marginTop:28,marginBottom:12,fontSize:22,fontWeight:'900'},record:{flexDirection:'row',gap:12,paddingVertical:13},dot:{width:12,height:12,borderRadius:6,backgroundColor:'#0E5A45',marginTop:5},recordCopy:{flex:1,paddingBottom:13,borderBottomWidth:1,borderBottomColor:'#E5E2DA'},recordTop:{flexDirection:'row',justifyContent:'space-between',gap:10},recordType:{fontSize:11,fontWeight:'900',textTransform:'uppercase',color:'#0E5A45'},recordDate:{fontSize:11,opacity:.55},recordTitle:{marginTop:6,fontSize:17,fontWeight:'900'},provider:{marginTop:5,fontSize:13,opacity:.62},notesText:{marginTop:6,fontSize:14,lineHeight:20,opacity:.68},empty:{padding:28,borderRadius:20,backgroundColor:'#FFF',alignItems:'center'},emptyIcon:{fontSize:38},emptyTitle:{marginTop:10,fontSize:18,fontWeight:'900'},muted:{marginTop:7,opacity:.55},error:{marginTop:10,color:'#A33A2B',lineHeight:20}});